lcr-modules:
    utils:
        inputs:
            bed:
                # add mor genome_build if running with multiple capture/exome kit
                grch37: "__UPDATE__"
        compress_to_cram: True

        options:
            bam_sort: ""
            bam_markdups: "--overflow-list-size 600000"
            bam_index: "-b"
            bam_to_cram: ""
## Lines commented out with `#!` are required for the module to run
## Lines commented out with `#?` can optionally be user-configured
## Lines commented out with `##` act as regular comments

        paired_modules: ["bwa_mem", "star"]
        ## See main README.md for how to set `samples` in the Snakefile
        #! samples: null

        scratch_subdirectories: []

        conda_envs:
            samtools: "envs/samtools-1.9.yaml"
            sambamba: "envs/sambamba-0.7.1.yaml"
            picard: "envs/picard-2.22.3.yaml"

        threads:
            bam_sort: 24
            bam_markdups: 24
            bam_index: 8
            interval: 2
            bam_to_cram: 8

        mem_mb:
            bam_sort: 48000
            bam_markdups: 48000
            bam_index: 8000
            interval: 8000
            bam_to_cram: 8000
