lcr-modules:
    
    rainstorm:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_maf: "__UPDATE__"

        scratch_subdirectories: []

        options:
            cohort_name: "__UPDATE__"
            genome_build: "__UPDATE__"
            max_mut: "__UPDATE__"

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            
        threads:
            rainstorm: 24
            doppler: 8

        resources:
            rainstorm: 
                mem_mb: 80000
            
        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
