lcr-modules:
    
    oncodriveclustl:

        dirs:
            _parent:

        g_build: # Updated by snakefile

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id} {normal_id} {pair_status}
            sample_set: "CLL_primary-only" 
            ## Set as the path to your MAF file or select from assorted sample sets:
    
            ## Choose from: 
            ## BL_DLBCL-BL-like_all
            ## BL_HGBL_DLBCL_FL_COMFL_CLL_MCL_B-ALL_PBL_DLBCL-BL-like_UNSPECIFIED_SCBC_MM_all
            ## CLL_MCL_FL_all
            ## CLL_primary-only
            ## DLBCL_COMFL_PBL_HGBL_DLBCL-BL-like_primary-only
            ## FL_primary-only
            ## MCL_all
            ## MM_all
            ## MM_non-primary-only
            ## MM_primary-only

            maf_nickname: 
            # Title for CLUSTL results files.
            # Extracted from the MAF file or sample set. Can also be set by user :-)

        coding_sequence: True # Use Boolean value

        scratch_subdirectories: []

        options:
            reference:
                    grch37: "-r /projects/nhl_meta_analysis_scratch/gambl/ref_local/oncodrive/oncodrive_files/hg19/hg19.cds.tsv.gz -g hg19"
                    hg38: "-r /projects/nhl_meta_analysis_scratch/gambl/ref_local/oncodrive/oncodrive_files/hg38/hg38.cds.tsv.gz -g hg38"
            clustl:

        conda_envs:
            #clustl: "{MODSDIR}/envs/oncodriveclustl-1.1.3.yaml"
            clustl: "/home/mcruz/lcr-modules/envs/oncodriveclustl/oncodriveclustl-1.1.3.yaml"
            
        threads:
            clustl: 4

        mem_mb:
            clust: 2000
            ## ?

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
