lcr-modules:
    
    oncodriveclustl:

        inputs:
            # Available wildcards: {seq_type} {genome_build}
            master_maf: "__UPDATE__"
            sample_sets: "__UPDATE__"

        sample_set: "__UPDATE__"
        genome_build: "__UPDATE__"
        seq_types: ["genome","capture"]
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.0/generate_smg_inputs.R"
        include_non_coding: False # True or False
        
        reference_files_directory: "__UPDATE__"
        regions_file:
            hg19: "__UPDATE__"
            hg38: "__UPDATE__"

        scratch_subdirectories: []

        options:
            clustl: ""

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            clustl: "{MODSDIR}/envs/oncodriveclustl-1.1.3.yaml"

        threads:
            clustl: 4

        resources:
            clustl:
                mem_mb: 20000

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            capture:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            mrna:  
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
