genome_builds:
    mm10: 
        version: "grcm38"
        provider: "ucsc"
        genome_fasta_url: "https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.fa.gz"

capture_space:
    exome-utr-mm10:
        genome: "grcm38"
        provider: "ucsc"
        default: "true"
        capture_bed_file: "/projects/rmorin/reference/mm10/mm10_all_genes.canonical.sort.bed4"
    # to add custom capture space, follow this example and fill in dictionary keys
    #name_of_capture_panel:
        #genome: "grch37" or "hg38" as example
        #provider: "ensembl" or "ucsc"
        #capture_bed_url: here provide a link enclosed in "" to download bed file for capture panel if it is available in internet
        #capture_bed_file: this key is optional and in "" you can specify path to a local bed file with capture panel

capture_params:
    padding_size: "200"

wildcard_values:
    gencode_release: ["M29"]
    dbsnp_build: ["151"]
    star_overhang: ["74", "99"]
    gc_window_size: ["50"]
    blacklist_version: ["hg19", "grch38"] 
    rm_version: ["hg19", "hg38"]

tools:
    bedtools:
        conda_env: "envs/bedtools-2.29.2.yaml"
        version: "2.29.2"
    coreutils: 
        conda_env: "envs/coreutils-8.31.yaml"
        version: "8.31"
    cvbio: 
        conda_env: "envs/cvbio-3.0.0.yaml"
        version: "3.0.0"
    samtools: 
        conda_env: "envs/samtools-1.9.yaml"
        version: "1.9"
    tabix:
        conda_env: "envs/tabix-0.2.6.yaml"
        version: "0.2.6"
    bwa: 
        conda_env: "envs/bwa-0.7.17.yaml"
        version: "0.7.17"
    star: 
        conda_env: "envs/star-2.7.3a.yaml"
        version: "2.7.3a"
    sequenza-utils:
        conda_env: "envs/sequenza-utils-3.0.0.yaml"
        version: "3.0.0"
    picard: 
        conda_env: "envs/picard-2.22.3.yaml"
        version: "2.22.3"
    ucsc-gtftogenepred:
        conda_env: "envs/ucsc-gtftogenepred-377.yaml"
        version: "377"
    bedops: 
        conda_env: "envs/bedops-2.4.39.yaml"
        version: "2.4.39"
    salmon: 
        conda_env: "envs/salmon-1.3.0.yaml"
        version: "1.3.0"
    gffread:
        conda_env: "envs/gffread-0.12.1.yaml"
        version: "0.12.1"
    gatk:
        conda_env: "envs/gatk-4.1.8.1.yaml"
        version: "4.1.8.1"
    gsutil: 
        conda_env: "envs/gsutil-4.53.yaml"
        version: "4.53"
    sigprofiler:
        conda_env: "envs/sigprofiler-1.1.yaml"
        version: "1.1"
    bcftools:
        conda_env: "envs/bcftools-1.10.2.yaml"
        version: "1.10.2"
    igblast:
        conda_env: "envs/igblast-1.17.1.yaml"
        version: "1.17.1"
    oncodriveclustl:
        conda_env: "envs/oncodriveclustl-1.1.3.yaml"
        version: "1.1.3"

cvbio_config:
    gtf: 
        comment: "#"
        columns: "0"
        skip: "false"
        delimiter: "\t"
    txt: 
        comment: "#"
        columns: "0"
        skip: "false"
        delimiter: "\t"
    vcf:
        comment: "#"
        columns: "0"
        skip: "false"
        delimiter: "\t"
    bed: 
        comment: "#"
        columns: "0"
        skip: "false"
        delimiter: "\t"
