lcr-modules:
    
    sniffles:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
        
        scratch_subdirectories: []

        conda_envs:
            sniffles: "{MODSDIR}/envs/sniffles-2.7.5.yaml"
            svtools: "{MODSDIR}/envs/svtools-0.5.1.yaml"
        container_envs:
            sniffles: "docker://quay.io/biocontainers/sniffles:2.0.3--pyhdfd78af_0"
            svtools: "docker://quay.io/biocontainers/svtools:0.5.1--py_0"


        threads:
            sniffles: 20
            vcf_to_bedpe: 1
            
        resources:
            sniffles:
                mem_mb: 25000
                bam: 1
            vcf_to_bedpe:
                mem_mb: 2000
        
        options:
            sniffles_args: "" # Update with desired Sniffles arguments. Suggested: --mosaic

        pairing_config:
            promethION:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
