lcr-modules:
    
    sniffles:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
        
        scratch_subdirectories: []

        conda_envs:
            sniffles: "{MODSDIR}/envs/sniffles.yaml"

        threads:
            sniffles: 20
            
        mem_mb:
            sniffles: 25000
            

        pairing_config:
            promethION:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
