lcr-modules:
    
    sigprofiler:

        inputs:
            # Available wildcards: {file}, {seq_type}, {genome_build}
            maf: "__UPDATE__"

            generator: "{MODSDIR}/src/python/run_generator.py"
            extractor: "{MODSDIR}/src/python/run_extractor.py"

        scratch_subdirectories: []

        conda_envs:
            sigprofiler: "{MODSDIR}/envs/sigprofiler-1.1.yaml"
            
        threads:
            generator: 1
            estimate: 25
            extract: 25
        mem_mb:
            generator: 20000
            estimate: 1000
            extract: 1000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
