lcr-modules:
    
    sigprofiler:

        inputs:
            # DOES NOT INTERPOLATE WILDCARDS
            # Provide concantenated MAF file (e.g., path/to/filename.{seq_type}.{genome_build}.maf)
            # Replace {genome_build} with actual build (i.e., hg38, grch37, etc) and 
            # {seq_type} with either genome or capture
            maf: "__UPDATE__"

            generator: "{MODSDIR}/src/python/run_generator.py"
            extractor: "{MODSDIR}/src/python/run_extractor.py"

        scratch_subdirectories: []

        conda_envs:
            sigprofiler: "{MODSDIR}/envs/sigprofiler-1.1.yaml"
            
        threads:
            generator: 1
            estimate: 25
            extract: 25
        mem_mb:
            generator: 20000
            estimate: 4000
            extract: 4000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
