lcr-modules:
    
    ichorcna:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"


        scratch_subdirectories: []

        options:
            readcounter:
                qual: 20 # only includes reads with mapping quality greater than 20
                binSize:  1000000 # set window size to compute coverage 
                # available binSizes are: 1000000, 500000, 50000, 10000
            run:
                ichorCNA_libdir: ""
                ichorCNA_rscript:  "{MODSDIR}/src/runIchorCNA.R"
                # use panel matching same bin size (optional)
                ichorCNA_normalPanel: 
                    "1000000": "inst/extdata/HD_ULP_PoN_{genome_build}_1Mb_median_normAutosome_median.rds"
                    "500000": "inst/extdata/HD_ULP_PoN_{genome_build}_500kb_median_normAutosome_median.rds"
                # must use gc wig file corresponding to same binSize (required)
                ichorCNA_gcWig:
                    "1000000": "inst/extdata/gc_{genome_build}_1000kb.wig"
                    "500000": "inst/extdata/gc_{genome_build}_500kb.wig"
                    "50000": "inst/extdata/gc_{genome_build}_50kb.wig"
                    "10000": "inst/extdata/gc_{genome_build}_10kb.wig"
                # must use map wig file corresponding to same binSize (required)
                ichorCNA_mapWig:  
                    "1000000": "inst/extdata/map_{genome_build}_1000kb.wig"
                    "500000": "inst/extdata/map_{genome_build}_500kb.wig"
                    "50000": "inst/extdata/map_{genome_build}_50kb.wig"
                    "10000": "inst/extdata/map_{genome_build}_10kb.wig"
                # use bed file if sample has targeted regions, eg. exome data (optional)
                ichorCNA_exons:  NULL
                ichorCNA_centromere:  
                    grch37: "inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt"
                    hg19: "inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt"
                    hs37d5: "inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt"
                    grch38: "inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt"
                    hg38: "inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt"
                ichorCNA_minMapScore: 0.75
                ichorCNA_fracReadsInChrYForMale: 0.002 # Threshold for fraction of reads in chrY to assign as male
                ichorCNA_genomeStyle:  # can set this to UCSC or NCBI
                    grch37: "NCBI"
                    hg19: "NCBI"
                    hs37d5: "NCBI"
                    grch38: "UCSC"
                    hg38: "UCSC"
                # chrs used for training ichorCNA parameters, e.g. tumor fraction. 
                ichorCNA_chrTrain:  
                    grch37: "c(1:22)"
                    hg19: "c(1:22)"
                    hs37d5: "c(1:22)"
                    grch38: "paste0('chr', c(1:22))"
                    hg38: "paste0('chr', c(1:22))"
                # non-tumor fraction parameter restart values; higher values should be included for cfDNA
                ichorCNA_normal:  "c(0.5,0.6,0.7,0.8,0.9,0.95)"
                # ploidy parameter restart values
                ichorCNA_ploidy:  "c(2,3,4)"
                ichorCNA_estimateNormal:  TRUE
                ichorCNA_estimatePloidy:  TRUE
                ichorCNA_estimateClonality: TRUE
                # states to use for subclonal CN
                ichorCNA_scStates:  "c(1,3)"
                # set maximum copy number to use
                ichorCNA_maxCN:  5
                # TRUE/FALSE to include homozygous deletion state # FALSE for low coverage libraries (ex. 0.1x) ; can turn on for higher coverage data (ex. >10x)
                ichorCNA_includeHOMD: FALSE
                # Exclude solutions if total length of subclonal CNAs > this fraction of the genome 
                ichorCNA_maxFracGenomeSubclone: 0.5
                # Exclude solutions if total length of subclonal CNAs > this fraction of total CNA length
                ichorCNA_maxFracCNASubclone: 0.7
                # control segmentation - higher (e.g. 0.9999999) leads to higher specificity and fewer segments
                # lower (e.g. 0.99) leads to higher sensitivity and more segments
                ichorCNA_txnE:  0.9399999
                # control segmentation - higher (e.g. 10000000) leads to higher specificity and fewer segments
                # lower (e.g. 100) leads to higher sensitivity and more segments
                ichorCNA_txnStrength:  10000
                ichorCNA_plotFileType:  "pdf"
                ichorCNA_plotYlim:  "c(-2,2)"


        conda_envs:
            ichorcna: "{MODSDIR}/envs/ichorcna.env.yaml"
            hmmcopy_utils: "{MODSDIR}/envs/hmmcopy_utils.env.yaml"

        threads:
            readcounter: 4
            run: 4

        resources:
            readcounter:
                mem_mb: 2000
                bam: 1
            run: 
                mem_mb: 2000
                bam: 1

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
