lcr-modules:
    
    ichorcna:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"


        scratch_subdirectories: []

        options:
            readcounter:
                readCounterScript: "{MODSDIR}/etc/readCounter"
                chrs:
                    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
                qual: 20
                binSize:  1000000 # set window size to compute coverage
            run:
                ichorCNA_libdir: /projects/dscott_prj/CCSRI_1500/lowpassWGS/envs/ichorcna/ichorCNA/
                ichorCNA_rscript:  /projects/dscott_prj/CCSRI_1500/lowpassWGS/src/R/runIchorCNA.R
                # use panel matching same bin size (optional)
                ichorCNA_normalPanel: /projects/dscott_prj/CCSRI_1500/lowpassWGS/envs/ichorcna/ichorCNA/inst/extdata/HD_ULP_PoN_1Mb_median_normAutosome_mapScoreFiltered_median.rds
                # must use gc wig file corresponding to same binSize (required)
                ichorCNA_gcWig: /projects/dscott_prj/CCSRI_1500/lowpassWGS/envs/ichorcna/ichorCNA/inst/extdata/gc_hg19_1000kb.wig
                # must use map wig file corresponding to same binSize (required)
                ichorCNA_mapWig:  /projects/dscott_prj/CCSRI_1500/lowpassWGS/envs/ichorcna/ichorCNA/inst/extdata/map_hg19_1000kb.wig
                # use bed file if sample has targeted regions, eg. exome data (optional)
                ichorCNA_exons:  NULL
                ichorCNA_centromere:  /projects/dscott_prj/CCSRI_1500/lowpassWGS/envs/ichorcna/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt
                ichorCNA_minMapScore: 0.75
                ichorCNA_chrs:  c(1:22, \"X\")
                ichorCNA_fracReadsInChrYForMale: 0.002
                ichorCNA_genomeBuild:  hg19
                ichorCNA_genomeStyle:  NCBI
                # chrs used for training ichorCNA parameters, e.g. tumor fraction. 
                ichorCNA_chrTrain:  c(1:22)
                # non-tumor fraction parameter restart values; higher values should be included for cfDNA
                ichorCNA_normal:  c(0.5,0.6,0.7,0.8,0.9,0.95)
                # ploidy parameter restart values
                ichorCNA_ploidy:  c(2,3)
                ichorCNA_estimateNormal:  TRUE
                ichorCNA_estimatePloidy:  TRUE
                ichorCNA_estimateClonality: TRUE
                # states to use for subclonal CN
                ichorCNA_scStates:  c(1,3)
                # set maximum copy number to use
                ichorCNA_maxCN:  5
                # TRUE/FALSE to include homozygous deletion state
                ichorCNA_includeHOMD: FALSE
                # Exclude solutions if total length of subclonal CNAs > this fraction of the genome 
                ichorCNA_maxFracGenomeSubclone: 0.5
                # Exclude solutions if total length of subclonal CNAs > this fraction of total CNA length
                ichorCNA_maxFracCNASubclone: 0.7
                # control segmentation - higher (e.g. 0.9999999) leads to higher specificity and fewer segments
                # lower (e.g. 0.99) leads to higher sensitivity and more segments
                ichorCNA_txnE:  0.9999
                # control segmentation - higher (e.g. 10000000) leads to higher specificity and fewer segments
                # lower (e.g. 100) leads to higher sensitivity and more segments
                ichorCNA_txnStrength:  10000
                ichorCNA_plotFileType:  pdf
                ichorCNA_plotYlim:  c(-2,2)


        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            ichorcna: "{MODSDIR}/envs/ichorcna.env.yaml"
            
        threads:
            readcounter: 4
            run: 4

        mem_mb:
            readcounter: 2000
            run: 2000

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
