lcr-modules:
    kallisto:
        inputs:
            fastq: ["results/bam2fastq-1.0/99-outputs/{seq_type}--{genome_build}/{sample_id}.1.fastq.gz", "results/bam2fastq-1.0/99-outputs/{seq_type}--{genome_build}/{sample_id}.2.fastq.gz"]
        options:
            quant: "-b 100" 
            # --pseudobam 
            # --genomebam --gtf <gtf_file> --chromosomes {chrom.tsv}
            strand:
                _default: ""
                forward: "--fr-stranded"
                reverse: "--rf-stranded"
        threads:
            quant: null
        mem_mb:
            quant: null

        pairing_config:
            genome:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: True
                run_paired_tumours_as_unpaired: False
            capture:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: True
                run_paired_tumours_as_unpaired: False
            mrna:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: False
                run_paired_tumours_as_unpaired: True

    #### TEMPORARY ###
    _shared:
        reference:
            grch37:
                kal_index: "/projects/clc/references/kallisto/0.45.1/GRCh37/transcriptome.idx"
                kal_gtf: "/projects/clc/references/kallisto/0.45.1/GRCh37/Homo_sapiens.GRCh38.96.gtf"
                kal_chrom: "/projects/clc/references/kallisto/0.45.1/GRCh37/Homo_sapiens.GRCh38.chrom.sizes.tsv"
            grch38:
                kal_index: "/projects/clc/references/kallisto/0.45.1/GRCh38/transcriptome.idx"
                kal_gtf: "/projects/clc/references/kallisto/0.45.1/GRCh38/Homo_sapiens.GRCh38.96.gtf"
                kal_chrom: "/projects/clc/references/kallisto/0.45.1/GRCh38/Homo_sapiens.GRCh38.chrom.sizes.tsv"
