lcr-modules:
    manta:
        inputs:
            sample_bam: null
            calc_manta_vaf: "{REPODIR}/lcr-scripts/python/calc_manta_vaf.py"
            manta_config: "{MODSDIR}/etc/manta_config.default.ini"
        dirs:
            _parent: null
        conda_envs: 
            manta: null
        options:
            configure:
                _prefix: ""
                _suffix: ""
                _default: ""
                mrna: "--rna"
                capture: "--exome"
            manta: "--mode local"
        threads:
            manta: 12
        mem_mb:
            manta: 6000
        pairing_config:
            genome:
                run_unpaired_tumours_with: "unmatched_normal"
            capture:
                run_unpaired_tumours_with: "unmatched_normal"
            mrna:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: False
                run_paired_tumours_as_unpaired: True
