modules:
    manta:
        inputs:
            sample_bam: null
            calc_manta_vaf: "{REPODIR}/scripts/python/calc_manta_vaf.py"
        outputs:
            bedpe: null
        dirs:
            _parent: null
        conda_envs: 
            manta: null
        options:
            configure: ""
            manta: "--mode local"
