lcr-modules:
    manta:
        inputs:
            sample_bam: null
            calc_manta_vaf: "{SCRIPTSDIR}/python/calc_manta_vaf.py"
            manta_config: "{MODSDIR}/etc/manta_config.default.ini"
        options:
            configure:
                mrna: "--rna"
                capture: "--exome"
            manta: "--mode local"
        conda_envs:
            tabix: null
            manta: null
            calc_manta_vaf: "{SCRIPTSDIR}/calc_manta_vaf/1.0/pyvcf-0.6.8.yaml"
            svtools: null
        threads:
            manta: 12
        mem_mb:
            manta: 6000
        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
