modules:
    manta:
        inputs:
            sample_bam: null
            calc_manta_vaf: "{REPODIR}/lcr-scripts/python/calc_manta_vaf.py"
        dirs:
            _parent: null
        conda_envs: 
            manta: null
        options:
            configure:
                _base: ""
                mrna: "--rna"
                capture: "--exome"
            manta: "--mode local"
