modules:
    manta:
        pairing_config:
            genome:
                run_unpaired_tumours_with: "unmatched_normal"
            capture:
                run_unpaired_tumours_with: "unmatched_normal"
            mrna:
                run_paired_tumour: False
                run_unpaired_tumours_with: "no_normal"
        inputs:
            sample_bam: null
            calc_manta_vaf: "{REPODIR}/lcr-scripts/python/calc_manta_vaf.py"
        dirs:
            _parent: null
        conda_envs: 
            manta: null
        options:
            configure:
                _base: ""
                mrna: "--rna"
                capture: "--exome"
            manta: "--mode local"
