lcr-modules:
    manta:
        inputs:
            sample_bam: null
            calc_manta_vaf: "{REPODIR}/lcr-scripts/python/calc_manta_vaf.py"
            manta_config: "{MODSDIR}/config/configManta.py.ini"
        dirs:
            _parent: null
        conda_envs: 
            manta: null
        options:
            configure:
                _prefix: ""
                mrna: "--rna"
                capture: "--exome"
                _suffix: ""
            manta: "--mode local"
        threads:
            manta: 12
        mem_mb:
            manta: 6000
