$schema: "http://json-schema.org/draft-06/schema#"

description: an entry in the sample sheet

properties:
    sample_id:
        type: string
        description: Sample ID
    patient_id:
        type: string
        description: Patient ID
    tissue_status:
        type: string
        description: Tumour or normal
    seq_type:
        type: string
        description: Type of sequencing data (genome, mrna, mirna, capture)
    ff_or_ffpe:
        type: string
        description: Fresh frozen (FF) or formalin-fixed paraffin-embedded (FFPE)

required:
    - sample_id
    - patient_id
    - tissue_status
    - seq_type
    - ff_or_ffpe
