lcr-modules:
  _shared:
    # lcr modules config
    lcr-modules: "/home/kyakimovich/repos/lcr-modules/"
    lcr-scripts: "/home/kyakimovich/repos/lcr-scripts/"
    root_output_dir: "/projects/rmorin/rmorin_scratch/prospective_rrDLBCL_trial_data/pipeline_outputs/"
    pairing_config:
      genome:
          run_paired_tumours: True
          run_unpaired_tumours_with: "unmatched_normal"
          run_paired_tumours_as_unpaired: False
      capture:
          run_paired_tumours: True
          run_unpaired_tumours_with: "no_normal"
          run_paired_tumours_as_unpaired: False
    # global_params for cfDNA pipeline workflows
    # Input and output
    samplesheet: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/samplesheets/LSARP_samples_current.tsv"
    # baseoutdir: deprecated, use root_output_dir
    ref_genome: "/projects/rmorin/reference/igenomes/Homo_sapiens/GSC/GRCh38/Sequence/WholeGenomeFasta/GRCh38_no_alt.fa"
    ref_genome_ver: "GRCh38"  # GRCh37 if GRCh37/hg19, GRCh38 if GRCh38/hg38
    captureregions: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/bed_files/pipeline_bed_files/twist_ctDNA_DLBCL_panel_grch38ashm_v1_9July2024.bed"
    captureregionsil: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/bed_files/pipeline_bed_files/twist_ctDNA_DLBCL_panel_grch38ashm_v1_9July2024.interval_list"  # Picard Interval List

  cfDNA_umi_workflow:
    # Should contain BWA indicies and samtools fai index in the same directory
    refgenome: "/projects/rmorin/reference/igenomes/Homo_sapiens/GSC/GRCh38/Sequence/BWAIndex/GRCh38_no_alt.fa"
    picard_refgenome: "/projects/rmorin/reference/igenomes/Homo_sapiens/GSC/GRCh38/Sequence/WholeGenomeFasta/GRCh38_no_alt.fa" # includes the .dict
    dbsnpvcf: "/projects/rmorin/reference/igenomes/Homo_sapiens/GSC/GRCh38/Annotation/Variation/dbSNP.151.all.withChr.vcf.gz"  # Should be BGzipped and TABIX indexed

    # path example with {sample} wildcard to fastq files
    fastq_r1_path: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/pipeline_outputs/bam_pipeline/pipeline_inputs/{sample}_R1.fastq.gz"
    fastq_r2_path: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/pipeline_outputs/bam_pipeline/pipeline_inputs/{sample}_R2.fastq.gz"
    fastq_dirs:
      - "/projects/rmorin/rmorin_scratch/prospective_rrDLBCL_trial_data/raw_data/"

    readgroup:
      centre: "GQuebec"
      platformunit: "ILLUMINA"
      platformmodel: "NextSeq"
      description: "CAPPSeq of lymphoma-associated genes"

    # Threads
    bwa_threads: 8
    duplexconsensus_threads: 8
    samtools_sort_threads: 4
    basequal_threads: 2
    # memory (mb)
    ann_umi_mem: 35000
    grp_umi_mem: 35000

    # Barcode an duplex information
    barcodelength: "8"
    barcodelocation: "8M+T"  # Location of the barcode. See https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures
    umiedits: "2"  # Would be warry of changing
    minreads: "0"  # DO NOT SET TO x UNLESS YOU WANT AT LEAST x READ(S) FROM **EACH** STRAND

    # Cleanup and sanitization
    max_base_qual: 70
    min_base_qual: 20
    tags_to_remove: {'ad', 'ac', 'bd', 'ae', 'be', 'bq', 'bc', 'aq'}

  cfDNA_SAGE_workflow:
      # SAGE specific parameters
      notlist: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/PON/99-PON/capture/ctDNA_panel--hg38/rrDLBCL_ctDNA/somaticvcf/ctDNA_panel_pon.vcf"
      ensembl: "/home/kyakimovich/repos/ctDNA_Pro_Pipeline/resources/ensemble_data_cache/38" # need to download, see README, change to 38 if needed
      sage_hotspots: "/home/kyakimovich/repos/ctDNA_Pro_Pipeline/resources/KnownHotspots.38.vcf.gz" # can be custom or hmf tools one
      max_depth: "100000"
      min_map_qual: "40"
      tumor_min_vaf: "0.005"
      tumor_soft_min_vaf: "0.01"

      # custom made for filtering purposes
      blacklist_manifest: "/home/kyakimovich/repos/ctDNA_Pro_Pipeline/resources/blacklist_for_pipeline_2024-11-20.txt"
      hotspot_manifest: "/home/kyakimovich/repos/ctDNA_Pro_Pipeline/resources/hotspots_for_pipeline_2024-07-19.txt"

      # vcf2maf specific parameters
      custom_enst: "/home/kyakimovich/repos/ctDNA_Pro_Pipeline/resources/custom_enst.hg38.txt"
      vep_data: "/projects/rmorin/reference/ensembl_vep_cache/"
      centre: "morin_lab"


      # Mask positions with a high incidence of N bases
      # mask_script: "src/mask_n_sites.py"
      mask_threshold: "0.05"  # Fraction of N bases at a position to mask it
      mask_count: "8"  # Minimum number of N bases required to mask a position

      # Post-filtering
      exac_max_freq: 0.01
      # blacklist: "resources/capture-hg38.clean_blacklist.txt"
      min_alt_depth: 3
      min_germline_depth: 8
      max_germline_alt: 6
      tumor_af_diff: 3  # VAF must be at least this much higher in the tumor than the normal

      # IGV screenshot annotation sources.
      cytoband: "/home/kyakimovich/repos/lcr-modules/modules/cfdna_pipeline/1.0/resources/cytoband.hg38.txt"
      genetrack: "/home/kyakimovich/repos/lcr-modules/modules/cfdna_pipeline/1.0/resources/gencode.v23.gtf.gz"

  cfDNA_patient_reports:
    report_template: "/home/kyakimovich/repos/ctDNA_Pro_Pipeline/patient_reports/report_template.ipynb"

  lymphgen:
    hg38_chainfile: "/projects/rmorin/reference/lcr-modules-references/genomes/hg38/chains/grch38/hg38ToHg19.over.chain"
    convert_coord: "/projects/rmorin/software/lcr-scripts/crossmap/1.1/convert_maf_coords.sh"
    inputs:
        # Available wildcards: {seq_type}, {tumour_id}, {normal_id}, {pair_status}, {genome_build}
        sample_maf: "pipeline_outputs/sage_pipeline/99-final/{tumour_id}.grch37.processed.maf" # Set in Snakefile 
        sample_seg: 
        # Each key below can be the file path, with wildcards, for the output of a CNV file produced by a specific cnv caller (eg. battenberg)
        # The order of the keys determine what which file paths to prioritize first
        #       eg. battenberg: "results/battenberg-1.2/99-outputs/seg/{seq_type}--projection/{tumour_id}--{normal_id}--{pair_status}.{tool}.{projection}.seg"
        #           sequenza: "results/sequenza-1.4/99-outputs/seg/{seq_type}--projection/{tumour_id}--{normal_id}--{pair_status}.{tool}.{projection}.seg"
        #    It will first look for that sample's battenberg cnv file and then sequenza 
        # Only uncomment the keys that have file paths that exist (always keep "empty" uncommented)
        # Add any additional keys before "empty"
        # If you don't have an CNV data, just include "empty" (an empty seg file), and the module will run without cnv data 
            # battenberg: "__UPDATE__"
            # sequenza: "__UPDATE__"
            # controlfreec: "__UPDATE__"
            # cnvkit: "__UPDATE__"
            empty: "{MODSDIR}/etc/empty.seg" 
        sample_sv_info: 
        # All the SV files will be merged with a final SV file created for each sample so the order of keys don't matter 
        # If there is no fish sv file put "{MODSDIR}/etc/empty_sv_fish.tsv" in key fish 
        # Always keep all three keys with real file paths 
            fish: "{MODSDIR}/etc/empty_sv_fish.tsv"
            other:
            # svar_master file path MUST contain "svar_master" and manta file path MUST NOT contain 
                #svar_master: ""
                #manta: ""
                empty_sv: "{MODSDIR}/etc/empty_svar_master.tsv" 
        # # Provide the path to a file containing a list of genes covered by targeted sequencing panels
        # One Hugo_Symbol or one Entrez ID per row. 
        # If any of your samples are targeted, the file path should point to a list of genes for your targeted panel. 
        # The capture_space wildcard should match the capture_space value in the samples table. 
        # Leave blank if only exome/genome sequencing. 
        gene_list: "/projects/rmorin_scratch/prospective_rrDLBCL_trial_data/bed_files/pipeline_bed_files/twist_ctDNA_DLBCL_panel_grch38ashm_v1_9July2024_genes.txt" # e.g. "data/bed/{capture_space}.gene_list.txt"
        # Path to the directory where LGenIC should be installed
        lgenic_exec: "/home/kyakimovich/repos/LGenIC"
        # The URL below matches the sha of the version of GAMBLR installed by the post-deploy script. 
        gamblr_config_url: "https://raw.githubusercontent.com/morinlab/GAMBLR/d8d643face5b67bdfe850aabcbfe26f82254a825/config.yml"
    
    pairing_config:
        genome:
            run_paired_tumours: True
            run_unpaired_tumours_with: "unmatched_normal"
            run_paired_tumours_as_unpaired: False
        capture:
            run_paired_tumours: True
            run_unpaired_tumours_with: "no_normal"
            run_paired_tumours_as_unpaired: False

    options:
        reformat_seg:  #  Default columns for Battenberg output
            Tumor_Sample_Barcode: "ID"
            chromosome: "chrom"
            start: "start"
            end: "end"
            CN: "log.ratio"
        add_svs:  # Use "" if N/A (you are not providing SVs)
            samplecol: ""
            bcl2col: ""
            # Note any field value not present in either true/false is considered NA
            bcl2truevalues: "" # Can use a list here
            bcl2falsevalues: ""
            bcl6col: ""
            # Note any field value not present in either true/false is considered NA
            bcl6truevalues: ""  # Can use a list
            bcl6falsevalues: ""
        lymphgen_input:
            seq_type: "targeted"  # Availible options: exome/genome (they do the same thing) and targeted (for panels)
            use_log_ratio: "True"
        lymphgen_run:
            lymphgen_path: "/home/kyakimovich/repos/LymphGen/LymphGen/Run_Lymphgen.R"
            lymphgen_sv: "{MODSDIR}/src/curate_svs_for_lymphgen.R"
        # Indicate a list of fusions to be used to determine if the sample has BCL2 or BCL6 rearrangement 
        # Defaults are below - change if needed
        real_bcl2: ["IGH", "IGL", "IGK"] 
        real_bcl6: ["CIITA", "MYC", "HIST1H2BK", "IGH", "IGL", "LEPREL1", "LRMP", "MBNL1", "PAX5", "RFTN1", "ZEB2", "IGK"]

    conda_envs:
        optparse: "{MODSDIR}/envs/r-optparse-1.6.yaml"
        sorted_containers: "{MODSDIR}/envs/sortedcontainers-2.4.0.yaml"
        gamblr: "{MODSDIR}/envs/gamblr.yaml"
