lcr-modules:
  _shared:
    # lcr modules config
    lcr-modules: ".../lcr-modules/"
    lcr-scripts: ".../lcr-scripts/"
    root_output_dir: ".../pipeline_outputs/"
    pairing_config:
      genome:
          run_paired_tumours: True
          run_unpaired_tumours_with: "unmatched_normal"
          run_paired_tumours_as_unpaired: False
      capture:
          run_paired_tumours: True
          run_unpaired_tumours_with: "no_normal"
          run_paired_tumours_as_unpaired: False
    # global_params for cfDNA pipeline workflows
    # Input and output
    samplesheet: ""
    # baseoutdir: deprecated, use root_output_dir
    ref_genome: ".../GRCh38_no_alt.fa"
    # panel info
    ref_genome_ver: "GRCh38"  # GRCh37 if GRCh37/hg19, GRCh38 if GRCh38/hg38

    # should be formatted as a dict. allows for multiple panels. "Panel_name_in_samplesheet : path_to_panel_file" -- samplesheet column is "capture_space"
    captureregions: {}

    # Picard Interval List, make using picard BedToIntervalList
    captureregionsil: {}  

  cfDNA_umi_workflow:
    # Should contain BWA indicies and samtools fai index in the same directory
    refgenome: ".../GRCh38_no_alt.fa"
    picard_refgenome: ".../GRCh38_no_alt.fa" # includes the .dict
    dbsnpvcf: ".../dbSNP.151.all.withChr.vcf.gz"  # Should be BGzipped and TABIX indexed

    # path example with {sample} wildcard to fastq files
    fastq_r1_path: ".../pipeline_outputs/bam_pipeline/pipeline_inputs/{sample}_R1.fastq.gz"
    fastq_r2_path: ".../pipeline_outputs/bam_pipeline/pipeline_inputs/{sample}_R2.fastq.gz"

    readgroup:
      centre: "morin_lab"
      platformunit: "ILLUMINA"
      platformmodel: "NextSeq"
      description: "CAPPSeq of lymphoma-associated genes"

    # Threads
    bwa_threads: 8
    duplexconsensus_threads: 8
    samtools_sort_threads: 4
    basequal_threads: 2
    # memory (mb)
    ann_umi_mem: 35000
    grp_umi_mem: 35000

    # Barcode an duplex information
    barcodelength: "8"
    barcodelocation: "8M+T"  # Location of the barcode. See https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures
    umiedits: "2"  # Would be warry of changing
    minreads: "0"  # DO NOT SET TO x UNLESS YOU WANT AT LEAST x READ(S) FROM **EACH** STRAND

    # Cleanup and sanitization
    max_base_qual: 70
    min_base_qual: 20
    tags_to_remove: {'ad', 'ac', 'bd', 'ae', 'be', 'bq', 'bc', 'aq'}

  cfDNA_SAGE_workflow:
      # SAGE specific parameters
      notlist: ".../PON/99-PON/capture/ctDNA_panel--hg38/rrDLBCL_ctDNA/somaticvcf/ctDNA_panel_pon.vcf"
      ensembl: "...resources/ensemble_data_cache/38" # need to download, see README, change to 38 if needed
      sage_hotspots: ".../resources/KnownHotspots.38.vcf.gz" # can be custom or hmf tools one
      high_conf_bed: ".../pipeline_bed_files/dumby_high_conf.bed" # use empty dumby bed if not calling outside of panel regions
      max_depth: "100000"

      # custom made for filtering purposes, create empty dumby files if not needed
      blacklist_manifest: ""
      hotspot_manifest: ""

      # vcf2maf specific parameters
      custom_enst: ".../resources/custom_enst.hg38.txt"
      vep_data: "..../ensembl_vep_cache/"
      centre: "morin_lab"


      # Mask positions with a high incidence of N bases
      # mask_script: "src/mask_n_sites.py"
      mask_threshold: "0.05"  # Fraction of N bases at a position to mask it
      mask_count: "8"  # Minimum number of N bases required to mask a position

      # SAGE filters
      # VAF
      hard_min_vaf: "0.002" # should be <= than tier specific cutoffs
      tumor_panel_min_vaf: "0.005" # first pass filter on panel positions

      # controls the proportion of good quality alt reads allowed in the normal vs the tumor, based on cumulative BQ scores
      panel_max_germ_rel_raw_bq: 0.08 # default is 0.04
      hotspot_max_germ_rel_raw_bq: 0.25 # default is 0.25

      min_germline_depth: 8
      max_normal_alt_depth: 10 # hard filter not applied to hotspot positions
      min_map_qual: "40"

      # Post-filtering
      min_alt_depth: 3
      exac_max_freq: 0.01
      # blacklist: "resources/capture-hg38.clean_blacklist.txt"
      tumor_af_diff: 3  # VAF must be at least this much higher in the tumor than the normal

      # IGV screenshot annotation sources.
      cytoband: ".../resources/cytoband.hg38.txt"
      genetrack: ".../resources/gencode.v23.gtf.gz"