lcr-modules:
    
    mutect2:

        inputs:
            # Available wildcards: {sample_id} {seq_type} {genome_build}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
            # candiate_positions may be a VCF, BED, or GATK interval list file. 
            # For capture data, this can be used to specify the capture space. 
            # If you don't want to provide candidate positions, leave this field as-is. 
            # Set additional interval parameters under options: mutect2_interval_rules. 
            # See https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists for how-to. 
            candidate_positions: "" 

        scratch_subdirectories: [] # Recommended: mutect2

        options:
            mutect2_run: ""
            mutect2_interval_rules: "" # E.g. -ip 50 -isr INTERSECTION int pads each position by 50 bp and creates an intersect of the candidate positions with each chromosome region
            mutect2_pileupsummaries:
                chrom: "17"
            mutect2_filter: ""
            mutect2_filter_passed: 
                "-f '.,PASS' "
                # Can be modified to filter on additional criteria using bcftools view syntax
                # For example, to remove all variants with -log10(POPAF) > 4.0: 
                #"-f '.,PASS' -i 'INFO/POPAF > 4'"


        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            gatk: "{MODSDIR}/envs/gatk-4.1.8.1.yaml"
            bcftools: "{MODSDIR}/envs/bcftools-1.10.2.yaml"
            
        threads:
            mutect2_run: 4
            mutect2_f1r2: 1
            mutect2_pileupsummaries: 1
            mutect2_contamination: 1
            mutect2_filter: 1
            mutect2_passed: 1
            mutect2_merge_vcfs: 10

        resources:
            mutect2_run:
                mem_mb: 10000
            mutect2_f1r2: 
                mem_mb: 10000
            mutect2_pileupsummaries: 
                mem_mb: 25000
            mutect2_contamination: 
                mem_mb: 2500
            mutect2_filter:
                mem_mb: 10000
            mutect2_passed:
                mem_mb: 2000
            mutect2_merge_vcfs:
                mem_mb: 10000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
