lcr-modules:
    fastqc:
        inputs:
            sample_bam: null
        dirs:
            _parent: null
        conda_envs: 
            fastqc: null
        options:
            fastqc: "--no-group"

        threads:
            fastqc: null
        mem_mb:
            fastqc: null

        pairing_config:
            genome:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: True
                run_paired_tumours_as_unpaired: False
            capture:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: True
                run_paired_tumours_as_unpaired: False
            mrna:
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours: False
                run_paired_tumours_as_unpaired: True
