lcr-modules:
    
    vcf2maf:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            vep_cache: "/projects/rmorin/reference/ensembl_vep_cache/"

        options:
            vcf2maf: "--filter-vcf 0"
            # --filter-vcf     A VCF for FILTER tag common_variant. Set to 0 to disable [~/.vep/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz]
            #--species        Ensembl-friendly name of species (e.g. mus_musculus for mouse) [homo_sapiens]
            #--cache-version  Version of offline cache to use with VEP (e.g. 75, 84, 91) [Default: Installed version]

        conda_envs:
            vcf2maf: "{MODSDIR}/envs/vcf2maf-1.6.17.yaml"
            
        threads:
            vcf2maf: 2

        mem_mb:
            vcf2maf: 4000
