modules:
    vcf2maf:
        inputs:
            vcf: "results/{caller}-1.0/99-outputs/{seq_type}/{tumour_id}--{normal_id}--{is_matched}/{var_type}.vcf"
            vep: "/projects/clc/references/vep/GRCh37/"
        dirs:
            _parent: null
        conda_envs: 
            vcf2maf: "/projects/clc/projects/hwinata/seq_workflow/lcr-modules/modules/vcf2maf/1.0/envs/from_history/vcf2maf.yaml"
        options:
            vcf2maf: "--filter-vcf 0 --ncbi-build {wildcards.genome_build} "
            # --filter-vcf     A VCF for FILTER tag common_variant. Set to 0 to disable [~/.vep/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz]
            #--species        Ensembl-friendly name of species (e.g. mus_musculus for mouse) [homo_sapiens]
            #--ncbi-build     NCBI reference assembly of variants MAF (e.g. GRCm38 for mouse) [GRCh37]
            #--cache-version  Version of offline cache to use with VEP (e.g. 75, 84, 91) [Default: Installed version]

        threads:
            vcf2maf: null
        memory:
            vcf2maf: null

# results/manta-1.0/01-manta/{seq_type}/{tumour_id}--{normal_id}--{is_matched}/results/variants/candidateSmallIndels.vcf.g