lcr-modules:
  _shared:
    lcr-modules: ""
    lcr-scripts: ""

  make_pon:
    pon_name: "rrDLBCL_ctDNA"
    repo_path: "...ctDNA_Pro_Pipeline"
    samplesheet: ""
    bam_dir: ""
    workdir: ""
    target_bed: ""
    genome_build: "GRCh38"
    # mutect2
    gnomad: ".../af-only-gnomad.normalized.hg38.vcf.gz"
    ref_fasta: ".../GRCh38_no_alt.fa"
    min_sample_count: 2 # min number of samples a var has to be called in to be included in the PON
    # vcf2maf
    vep_data: ".../ensembl_vep_cache/"
    centre: "morin_lab"

    gatk_env: "envs/gatk.yaml"
    bcftools_env: "envs/bcftools.yaml"

    resources:
      mutect:
        mem_mb: 16000
      concatenate_vcf:
        mem_mb: 16000