lcr-modules:

    ecotyper:

        inputs:
            ge_matrix: "__UPDATE__"
            annotations: "__UPDATE__"

        scratch_subdirectories: []

        options:
            ecotyper_version: "cc92e8c" # here the sha for the commit of ecotyper version can be specified to clone a specific version
            annotation_tracks: "-c pathology" # comma-separated list of columns from metadata to plot as annotations on heatmap

        conda_envs:
            ecotyper: "{MODSDIR}/envs/ecotyper.yaml"

        threads:
            processing: 2
            ecotyper: 16

        resources:
            processing:
                mem_mb: 20000
            ecotyper:
                mem_mb: 40000

        pairing_config:
            mrna:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
