lcr-modules:

    ecotyper:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            ge_matrix: "__UPDATE__"
            annotations: "__UPDATE__"

        scratch_subdirectories: []

        options:
            ecotyper_version: "cc92e8c" # here the sha for the commit of ecotyper version can be specified to clone a specific version


        conda_envs:
            ecotyper: "{MODSDIR}/envs/ecotyper.yaml"

        threads:
            preprocessing: 2

        resources:
            preprocessing:
                mem_mb: 20000

        pairing_config:
            mrna:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
