lcr-modules:
    
    gistic2:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_seg: "__UPDATE__"

        projections: ["grch37", "hg38"]

        scratch_subdirectories: []

        options:
            gistic2_run:
                conf_level: "90"
                gene_collapse_method: "extreme"
                max_segs_per_sample: "5000"
                broad_len_cutoff: "0.5"
                join_segment_size: "1"
                qv_thresh: "0.5"
                t_del: "0.05"

        conda_envs:
            gistic2: "{MODSDIR}/envs/gistic2-2.0.23.yaml"
            
        # I believe this isn't needed
        threads:
            gistic2_run: 4

        resources:
            gistic2_run: 
                mem_mb: 2000
            
        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: False
