lcr-modules:
    
    pti:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_maf: "__UPDATE__"

        scratch_subdirectories: []

        options:
            generate_input: 
                header_row: 1 # 0-based index of the row containing the MAF file header. If your MAF file has a "# version" header row, set this to 1. If the top row starts with hugo_symbol, set to 0. 
            step_2: ""

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            
        threads:
            step_1: 4

        mem_mb:
            step_1: 2000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
