lcr-modules:
    
    {{cookiecutter.module_name}}:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_{{cookiecutter.input_file_type}}: "__UPDATE__"

        scratch_subdirectories: []

        options:
            step_1: ""
            step_2: ""

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            
        threads:
            step_1: 4

        resources:
            step_1: 
                mem_mb: 2000
            
        pairing_config:
        {%- for seq_type, mode in cookiecutter.items() if seq_type.startswith("seq_type.") %}
            {%- if mode != "omit" %}
            {{ seq_type | replace("seq_type.", "", 1) }}:
            {%- if mode == "matched_only" %}
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
            {%- elif mode == "allow_unmatched" %}
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            {%- elif mode == "no_normal" or mode == "unpaired" %}
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            {%- endif %}
            {%- endif %}
        {%- endfor %}
