lcr-modules:

    mutationtimer:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {genome_build} {tumour_id} {normal_id}
            # Use non-filled battenberg files: results/gambl/battenberg-1.1/02-battenberg/genome--{genome_build}/{tumour_id}--{normal_id}/{tumour_id}_subclones.txt
            battenberg_txt: "__UPDATE__"
            cellularity_txt: "__UPDATE__"
            gamblr_config_url: "https://raw.githubusercontent.com/morinlab/GAMBLR.results/f92c22ac286822178415a3b6a818251effc56890/config.yml"

        scratch_subdirectories: []

        options:
            liftover_script_path: "{SCRIPTSDIR}/liftover/1.0/liftover.sh"
            liftover_minMatch: 0.95
            mutationtimer_script: "{MODSDIR}/src/MutationTimeR.R"
            n_bootstrap: 200

        conda_envs:
            liftover: "{SCRIPTSDIR}/liftover/1.0/liftover.yaml"
            mutationtimer: "{MODSDIR}/envs/MutationTimeR.yml"

        threads:
            mutationtimer: 4

        resources:
            mutationtimer:
                mem_mb: 5000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
