lcr-modules:

    mutationtimer:

        inputs:
            # Available wildcards: {genome_build} {tumour_id} {normal_id}
            # Use battenberg files: results/gambl/battenberg-1.1/99-outputs/txt/genome--{genome_build}/{tumour_id}--{normal_id}_subclones.txt
            battenberg_txt: "__UPDATE__"
            cellularity_txt: "__UPDATE__"
            # Available wildcards: {projection} {tumour_id} {normal_id}
            # Use SLMS-3 vcf2maf merged augmented mafs: results/all_the_things/slms_3-1.0_vcf2maf-1.3/genome--projection/deblacklisted/augmented_maf/all_slms-3--{projection}.maf
            augmented_maf: "__UPDATE__"

        scratch_subdirectories: []

        options:
            liftover_script: "{SCRIPTSDIR}/liftover/1.0/liftover.sh"
            liftover_minMatch: 0.95
            resolve_overlaps_script: "{MODSDIR}/src/resolve_overlaps.R"
            mutationtimer_script: "{MODSDIR}/src/MutationTimeR.R"
            n_bootstrap: 200

        conda_envs:
            liftover: "{SCRIPTSDIR}/liftover/1.0/liftover.yaml"
            mutationtimer: "{MODSDIR}/envs/mutationtimer.yml"

        threads:
            mutationtimer: 4

        resources:
            mutationtimer:
                mem_mb: 5000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
