lcr-modules:

    purecn:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {tumour_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"

            # Available wildcards: {seq_type} {genome_build} {tumour_id}
            cnvkit_seg: "__UPDATE__"
            cnvkit_cnr: "__UPDATE__"

            # From _panel_of_normals
            # Available wildcards: {seq_type} {genome_build} {capture_space}
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/baits_{capture_space}_intervals.txt
            purecn_intervals: "__UPDATE__"
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/baits_{capture_space}_intervals_gatk.list
            gatk_intervals: "__UPDATE__"
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/baits_{capture_space}_intervals_gatk_targets_sorted.list
            gatk_targets: "__UPDATE__"
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/{capture_space}_mutect2_pon.vcf.gz and it's index
            mutect2_pon: "__UPDATE__"
            mutect2_pon_tbi: "__UPDATE__"
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/purecn_cnvkit_normal/mapping_bias_{genome_build}_{capture_space}.rds
            cnvkit_mapping_bias: "__UPDATE__"
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/purecn_denovo_normal/mapping_bias_{genome_build}_{capture_space}.rds
            denovo_mapping_bias: "__UPDATE__"
            # panel_of_normals-1.0/99-outputs/purecn/{seq_type}--{genome_build}/{capture_space}/purecn_denovo_normal/normalDB_{genome_build}_{capture_space}.rds
            denovo_normal_db: "__UPDATE__"
            
            

        scratch_subdirectories: []

        # Acceptable values: "purecn_denovo", "purecn_cnvkit"
        modes:  ["purecn_cnvkit", "purecn_denovo"]
        requested_projections: ["grch37", "hg38"]

        options:
            mutect2:
                mutect2_opts: ""
                annotate: "" # for gatk FilterMutectCalls which just annotates variants for later filtering when this is blank
                # the following two are for the call to bcftools that actually filters the variants
                filter_for: -f '.,PASS,germline' # Do not wrap in double quotes!
                filter_out: "FILTER~'weak_evidence' | FILTER~'contamination' | INFO/AS_FilterStatus~'weak_evidence' | INFO/AS_FilterStatus~'contamination'"
            coverage:
                depth_coverage: ""
                force: "--force"
                opts: ""
            genome_builds_map:
                grch37: "hg19"
                hg19: "hg19"
                hs37d5: "hg19"
                grch38: "hg38"
                hg38: "hg38"
                hg38-nci: "hg38"
            cnvkit_mode:
                alpha: "0.001"
                max_cn: "8"
                model: "betabin"
                min_offtarget: "0.05"
                opts: "--force --post-optimize --seed 123 "
            denovo_mode:
                alpha: "0.001"
                max_cn: "8"
                model: "betabin"
                min_offtarget: "0.05"
                opts: "--force --post-optimize --seed 123 "
            cnv2igv_script_path: "{SCRIPTSDIR}/cnv2igv/1.5/cnv2igv.py"
            # cnv2igv preserve log.ratio or change this to "" to calculate it from the absolute CN
            preserve: "--preserve_log_ratio"
            # liftOver options to convert between genomic builds
            liftover_script_path: "{SCRIPTSDIR}/liftover/2.0/liftover.sh"
            liftover_minMatch: "0.95" # Float number from 0 to 1 indicating minimal mapping when converting to a different genome build
            fill_segments_version: "1.2/"
            
        software:
            coverage_script: "{MODSDIR}/etc/Coverage.R"
            tidy_pureCN_script: "{MODSDIR}/etc/Tidy_pureCN_seg.sh"

        conda_envs:
            mutect: "{MODSDIR}/envs/gatk-4.1.8.1.yaml"
            bcftools: "{MODSDIR}/envs/bcftools-1.10.2.yaml"
            purecn: "{MODSDIR}/envs/purecn-2.0.1.yaml"
            bedtools: "{MODSDIR}/envs/bedtools-2.29.2.yaml"
            cnv2igv: "{SCRIPTSDIR}/cnv2igv/1.5/python-3.8.3.yaml"
            liftover: "{SCRIPTSDIR}/liftover/2.0/liftover.yaml"

        threads:
            post_vcf: 2
            coverage: 2
            cnvkit_mode: 4
            denovo_mode: 4

        resources:
            mutect:
                mem_mb: 40000
                chrom: 1
            post_vcf:
                mem_mb: 8000
            gatk_depth:
                mem_mb: 15000
                chrom: 1
            coverage:
                mem_mb: 18000
            cnvkit_mode:
                mem_mb: 90000
            denovo_mode:
                mem_mb: 90000
            post_purecn:
                mem_mb: 2000


        pairing_config:
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
