lcr-modules:
    
    salmon:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_fastq_1: "__UPDATE__"
            sample_fastq_2: "__UPDATE__"
            # This script from lcr-scripts will generate counts matrix for all samples
            salmon2counts: "{SCRIPTSDIR}/salmon2counts/1.0/salmon2counts.R"

        options:
            # tells salmon to automatically determine library type (e.g. stranded vs. unstranded etc.)
            quant: "-l A"

        transcriptome:
            # Specify the transcriptome build for quantification
            quant_to: "__UPDATE__" # Options: "hg19", "hg38", "mm10"

        conda_envs:
            salmon: "{MODSDIR}/envs/salmon-1.3.0.yaml"
            salmon2counts: "{SCRIPTSDIR}/salmon2counts/1.0/salmon2counts.yaml"
            
        threads:
            quant: 4

        resources:
            quant: 
                mem_mb: 10000
            matrix: 
                mem_mb: 10000

        group: 
            quant: "quant" # For efficient temp file deletion, change to match group parameter for bam2fastq.

        pairing_config:
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
