lcr-modules:
    
    fishhook:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            master_maf: "__UPDATE__"
            tiles_size: "__UPDATE__"
            

        scratch_subdirectories: []

        src_dir: "{MODSDIR}/src/"

        options:


        conda_envs:
            fishhook: "{MODSDIR}/envs/fishhook.yaml"
            
        threads:
            fishhook: 1

        resources:
            fishhook: 
                mem_mb: 2000
            
        pairing_config:
