lcr-modules:
    
    fishhook:
        inputs:
            # Available wildcards: {seq_type}
            master_maf: "__UPDATE__"
            sample_sets: "__UPDATE__"

        sample_set: ["test"]
        seq_types: ["genome", "capture"]
        include_non_coding: True
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.0/generate_smg_inputs.R"
        src_dir: "{MODSDIR}/src/"

        options:
            include_silent_mutation: True #Include silent mutation in maf file
            tiles_size: 1000  #This is the size of tiles you want to split the genome into, leave blank if you want to use a gene list as hypothese
            target_gene_list: "" #If you do not provide a tile size, please provide a gene list in gtf format (e.g GENCODE v19 genes for GRCH37: gencode.v19.genes.gtf) for Fishhook to do a gene-centric analysis
            target_gene_list_only_protein_coding: True #Only include protein coding genes in gene list
            covariates: "" #please supply a coveriate file in bed format, leave it blank if you want to run FishHook without covariates

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            fishhook: "{MODSDIR}/envs/fishhook.yaml"
            
        threads:
            fishhook: 1

        resources:
            fishhook: 
                mem_mb: 16000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False           
