lcr-modules:
    
    fishhook:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            master_maf: "../../../fishhook/data_dlbcl_full.maf"
            
        src_dir: "{MODSDIR}/src/"

        options:
            tiles_size: 1000

        conda_envs:
            fishhook: "{MODSDIR}/envs/fishhook.yaml"
            
        threads:
            fishhook: 1

        resources:
            fishhook: 
                mem_mb: 10000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False           
