lcr-modules:
    
    fishhook:
        inputs:
            # Available wildcards: {seq_type}
            master_maf: "../../../fishhook/data_dlbcl_full.maf"
            sample_sets: "../../../fishhook/sample_id.tsv"

        sample_set: ["test"]
        seq_types: ["genome", "capture"]
        include_non_coding: True
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.0/generate_smg_inputs.R"
        src_dir: "{MODSDIR}/src/"


        options:
            tiles_size: 1000

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            fishhook: "{MODSDIR}/envs/fishhook.yaml"
            
        threads:
            fishhook: 1

        resources:
            fishhook: 
                mem_mb: 10000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False           
