lcr-modules:

    hmftools:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
            # Available wildcards: {seq_type} {genome_build} {tumour_id}
            # Note: SLMS-3 outputs are recommended.
            # The pipeline will take any VCF where the samples are labeled 'TUMOR' and 'NORMAL',
            # and where the VCF is annotated with "AD" and "DP" fields.
            # Must be in bgzip with `.vcf.gz` extension.
            slms3_vcf: "__UPDATE__"
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            # Note: These are output by the gripss somatic filtering step of the gridss module
            gridss_somatic: "__UPDATE__" # Output of GRIPSS
            gridss_somatic_tbi: "__UPDATE"
            gridss_somatic_filtered: "__UPDATE__" # Filtered output of GRIPSS
            gridss_somatic_filtered_tbi: "__UPDATE__"

        scratch_subdirectories: []

        switches:
            ensembl_url:
                '37': "mysql://ensembldb.ensembl.org:3337/homo_sapiens_core_89_37"
                '38': "mysql://ensembldb.ensembl.org:3306/homo_sapiens_core_98_38"

        options:
            version_map: # How genome_builds in samples table map to build numbers in hmftools reference files.
                # genome_build: ["37|38"]
                grch37: "37" # No chr prefixes (hg19 not allowed)
                hs37d5: "37"
                hg38: "38" # Mandatory chr prefixes (grch38 not allowed)
            use_masked_ref: False
            amber:
                -validation_stringency SILENT
            cobalt:
                -validation_stringency SILENT
            purple: ""
            linx: ""
            linx_viz:
                -fusion_legend_height_per_row 70
                -segment_relative_size 0.5
                -outer_radius 0.85
                -min_line_size 4
                -max_line_size 18
                -min_label_size 45
                -max_label_size 50
                -glyph_size 25
                -exon_rank_radius 0.04
                -max_gene_characters 15
            linx_viz_annotate:
                -fusion_legend_height_per_row 70
                -segment_relative_size 0.5
                -outer_radius 0.85
                -min_line_size 4
                -max_line_size 18
                -min_label_size 45
                -max_label_size 50
                -glyph_size 25
                -exon_rank_radius 0.04
                -max_gene_characters 15

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            wget: "{MODSDIR}/envs/wget-1.20.1.yaml"
            bcftools: "{MODSDIR}/envs/bcftools-1.10.2.yaml"
            amber: "{MODSDIR}/envs/hmftools-amber-3.5.yaml"
            cobalt: "{MODSDIR}/envs/hmftools-cobalt-1.11.yaml"
            purple: "{MODSDIR}/envs/hmftools-purple-2.54.yaml"
            linx: "{MODSDIR}/envs/hmftools-linx-1.15.yaml"
            linx_annotate: "{MODSDIR}/envs/hmftools-linx-1.15.yaml"
            snpeff: "{MODSDIR}/envs/snpeff-4.3.1t.yaml"

        threads:
            vcf_sample_names: 1
            snpeff: 4
            amber: 16
            cobalt: 16
            purple: 8
            linx: 2
            linx_viz: 8

        resources:
            vcf_sample_names:
                mem_mb: 1000
            snpeff:
                mem_mb: 5000
            amber:
                mem_mb: 36000
            cobalt:
                mem_mb: 20000
            purple:
                mem_mb: 20000
            linx:
                mem_mb: 10000
            linx_viz:
                mem_mb: 20000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
