#!/usr/bin/env Rscript
# Reformats mhc_hammer's own {patient_id}_mutations.csv (module-generated by
# _mhc_hammer_parse_mutations -- see make_mutation_table.R -- not an upstream MHC Hammer file)
# into a MAF-like table for tools that expect MAF input (e.g. maftools) but don't need real
# genomic coordinates for HLA. mhc_hammer calls mutations against each patient's own
# personalised, allele-specific reference FASTA -- one contig per typed HLA allele, named after
# the allele itself (e.g. "A*02:01:01:01", confirmed by reading upstream's own
# create_gtf_and_ref.R). There is no shared coordinate system across alleles or samples: the same
# base position in two different alleles' sequences (or the same allele called for two different
# patients) has no relationship to each other. Chromosome/Start_Position/End_Position/NCBI_Build
# below are therefore synthetic placeholders, not real genome coordinates -- everything else that
# can be derived from the real VEP/Mutect2 output in mutations.csv is filled in for real.
#
# Only rows where mutect_filter == "PASS" are kept (also drops rows where a mutation was called
# in one of the patient's tumour samples but only backfilled via BAM read counts, not actually
# called, in another -- those have mutect_filter == NA).
#
# Module-owned code, not adapted from any upstream MHC Hammer bin/*.R script -- this only
# post-processes this module's own already-generated mutations.csv.

suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(argparse))

parser <- ArgumentParser()
parser$add_argument('--mutations_csv', nargs = 1, required = TRUE)
parser$add_argument('--patient_id', nargs = 1, required = TRUE)
parser$add_argument('--output_maf', nargs = 1, required = TRUE)
args <- parser$parse_args()

maf_cols <- c(
  "Hugo_Symbol", "Entrez_Gene_Id", "Center", "NCBI_Build", "Chromosome",
  "Start_Position", "End_Position", "Strand", "Variant_Classification",
  "Variant_Type", "Reference_Allele", "Tumor_Seq_Allele1", "Tumor_Seq_Allele2",
  "dbSNP_RS", "dbSNP_Val_Status", "Tumor_Sample_Barcode",
  "Matched_Norm_Sample_Barcode", "Match_Norm_Seq_Allele1", "Match_Norm_Seq_Allele2",
  "Mutation_Status", "Sequencer", "t_depth", "t_ref_count", "t_alt_count",
  "n_depth", "n_ref_count", "n_alt_count", "Consequence", "IMPACT",
  "Transcript_ID", "Protein_position", "Codons", "Exon_Number", "HGVSp_Short",
  "Filter", "Called_By_Mutect", "HLA_Allele", "HLA_Allele_Position"
)

write_empty_maf <- function(path) {
  writeLines(paste(maf_cols, collapse = "\t"), path)
  cat("No mutations for", args$patient_id, "-- wrote header-only MAF to", path, "\n")
}

if (!file.exists(args$mutations_csv) || file.size(args$mutations_csv) == 0) {
  write_empty_maf(args$output_maf)
  quit(save = "no", status = 0)
}

muts <- fread(args$mutations_csv)

if (nrow(muts) == 0) {
  write_empty_maf(args$output_maf)
  quit(save = "no", status = 0)
}

# Only PASS-filtered Mutect2 calls belong in the MAF. This also naturally drops rows where
# mutect_filter is NA (called_by_mutect == FALSE -- a tumour sample that didn't actually have
# this mutation called, only backfilled with BAM read counts for context by
# make_mutation_table.R): NA == "PASS" is NA, and data.table row-filtering treats NA as FALSE.
muts <- muts[mutect_filter == "PASS"]

if (nrow(muts) == 0) {
  write_empty_maf(args$output_maf)
  quit(save = "no", status = 0)
}

# --- Hugo_Symbol: mhc_hammer's personalised reference contigs are named after the typed HLA
# allele itself -- the gene is the token before the first "*" (e.g. "A*02:01:01:01" -> "HLA-A").
muts[, Hugo_Symbol := paste0("HLA-", sub("\\*.*", "", chrom))]

# --- VCF -> MAF allele trimming (real, derived from ref/alt/mut_type -- not a placeholder).
# make_mutation_table.R's mut_type derivation guarantees INS has nchar(ref)==1 and DEL has
# nchar(alt)==1 (standard left-anchored VCF indel representation), so the anchor base is always
# the first character of the longer allele.
trim_alleles <- function(ref, alt, mut_type) {
  if (mut_type == "INS" && nchar(ref) == 1 && substr(alt, 1, 1) == ref) {
    list(ref = "-", alt = substring(alt, 2))
  } else if (mut_type == "DEL" && nchar(alt) == 1 && substr(ref, 1, 1) == alt) {
    list(ref = substring(ref, 2), alt = "-")
  } else {
    list(ref = ref, alt = alt)
  }
}
trimmed <- mapply(trim_alleles, muts$ref, muts$alt, muts$mut_type, SIMPLIFY = FALSE)
muts[, Reference_Allele := vapply(trimmed, `[[`, character(1), "ref")]
muts[, Tumor_Seq_Allele2 := vapply(trimmed, `[[`, character(1), "alt")]
# Somatic-only calls have no independently-genotyped tumour allele -- Tumor_Seq_Allele1
# conventionally mirrors Reference_Allele here, matching vcf2maf's own convention for VCFs
# without a tumour GT field.
muts[, Tumor_Seq_Allele1 := Reference_Allele]

muts[, Variant_Type := fcase(
  mut_type == "SNV", "SNP",
  mut_type == "INS", "INS",
  mut_type == "DEL", "DEL",
  mut_type == "MNV" & nchar(ref) == 2, "DNP",
  mut_type == "MNV" & nchar(ref) == 3, "TNP",
  mut_type == "MNV" & nchar(ref) > 3, "ONP",
  default = "COMPLEX" # not a standard MAF Variant_Type -- mhc_hammer's own "COMPLEX" mut_type has no MAF equivalent
)]

# --- Variant_Classification: standard VEP SO-term -> MAF classification mapping (the same table
# vcf2maf-like tools use), applied to the *most severe* consequence term when VEP reports more
# than one. vep_consequence is "&"-joined and already alphabetically sorted by
# _mhc_hammer_parse_mutations's own upstream script, so severity has to be re-derived here.
so_severity <- c(
  "transcript_ablation", "exon_loss_variant", "splice_acceptor_variant", "splice_donor_variant",
  "stop_gained", "frameshift_variant", "stop_lost", "start_lost", "initiator_codon_variant",
  "disruptive_inframe_insertion", "disruptive_inframe_deletion", "inframe_insertion",
  "inframe_deletion", "protein_altering_variant", "missense_variant",
  "conservative_missense_variant", "rare_amino_acid_variant", "transcript_amplification",
  "splice_region_variant", "start_retained_variant", "stop_retained_variant",
  "synonymous_variant", "coding_sequence_variant", "mature_miRNA_variant",
  "5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant",
  "non_coding_exon_variant", "intron_variant", "NMD_transcript_variant",
  "non_coding_transcript_variant", "nc_transcript_variant", "upstream_gene_variant",
  "downstream_gene_variant", "TFBS_ablation", "TFBS_amplification", "TF_binding_site_variant",
  "regulatory_region_ablation", "regulatory_region_amplification", "feature_elongation",
  "regulatory_region_variant", "feature_truncation", "intergenic_variant"
)

so_to_maf <- c(
  transcript_ablation = "Splice_Site", exon_loss_variant = "Splice_Site",
  splice_acceptor_variant = "Splice_Site", splice_donor_variant = "Splice_Site",
  stop_gained = "Nonsense_Mutation", stop_lost = "Nonstop_Mutation",
  start_lost = "Translation_Start_Site", initiator_codon_variant = "Translation_Start_Site",
  disruptive_inframe_insertion = "In_Frame_Ins", disruptive_inframe_deletion = "In_Frame_Del",
  inframe_insertion = "In_Frame_Ins", inframe_deletion = "In_Frame_Del",
  protein_altering_variant = "Missense_Mutation", missense_variant = "Missense_Mutation",
  conservative_missense_variant = "Missense_Mutation", rare_amino_acid_variant = "Missense_Mutation",
  transcript_amplification = "Intron", splice_region_variant = "Splice_Region",
  start_retained_variant = "Silent", stop_retained_variant = "Silent",
  synonymous_variant = "Silent", coding_sequence_variant = "Missense_Mutation",
  mature_miRNA_variant = "RNA", "5_prime_UTR_variant" = "5'UTR", "3_prime_UTR_variant" = "3'UTR",
  non_coding_transcript_exon_variant = "RNA", non_coding_exon_variant = "RNA",
  intron_variant = "Intron", NMD_transcript_variant = "Silent",
  non_coding_transcript_variant = "RNA", nc_transcript_variant = "RNA",
  upstream_gene_variant = "5'Flank", downstream_gene_variant = "3'Flank",
  TFBS_ablation = "IGR", TFBS_amplification = "IGR", TF_binding_site_variant = "IGR",
  regulatory_region_ablation = "IGR", regulatory_region_amplification = "IGR",
  feature_elongation = "IGR", regulatory_region_variant = "IGR", feature_truncation = "IGR",
  intergenic_variant = "IGR"
)

most_severe_classification <- function(consequence, mut_type) {
  if (is.na(consequence) || consequence == "") return(NA_character_)
  terms <- strsplit(consequence, "&", fixed = TRUE)[[1]]
  ranked <- so_severity[so_severity %in% terms]
  if (length(ranked) == 0) return(NA_character_)
  top <- ranked[1]
  if (top == "frameshift_variant") {
    return(if (identical(mut_type, "INS")) "Frame_Shift_Ins" else "Frame_Shift_Del")
  }
  unname(so_to_maf[top])
}
muts[, Variant_Classification := mapply(most_severe_classification, vep_consequence, mut_type)]

# --- HGVSp_Short-style amino acid change, when VEP reported both fields (e.g. "L/F" + "54" -> "p.L54F")
build_hgvsp <- function(aa, pos) {
  if (is.na(aa) || aa == "" || is.na(pos) || pos == "" || !grepl("/", aa, fixed = TRUE)) return(NA_character_)
  parts <- strsplit(aa, "/", fixed = TRUE)[[1]]
  if (length(parts) != 2) return(NA_character_)
  paste0("p.", parts[1], pos, parts[2])
}
muts[, HGVSp_Short := mapply(build_hgvsp, vep_amino_acids, vep_protein_position)]

# --- dbSNP_RS: pass through VEP's own existing_variation lookup when it's a real rsID
muts[, dbSNP_RS := ifelse(grepl("^rs[0-9]", vep_existing_variation), vep_existing_variation, "novel")]

# --- Synthetic, non-genomic Start/End "positions" -- see header note. Assigns one integer per
# distinct (chrom, pos, ref, alt) combination in this patient's file, so the same real mutation
# recurring across this patient's tumour samples keeps the same synthetic position (useful for
# tools that key rows by Chromosome+Start_Position+Ref+Alt), without implying any real spatial
# meaning -- these are NOT genomic coordinates.
variant_key <- paste(muts$chrom, muts$pos, muts$ref, muts$alt, sep = ":")
muts[, Start_Position := match(variant_key, unique(variant_key))]
muts[, End_Position := Start_Position + nchar(Reference_Allele) - 1]
muts[Reference_Allele == "-", End_Position := Start_Position + 1] # insertion convention: End = Start + 1

muts[, Chromosome := "6"] # real: HLA-A/B/C all sit on chr6 -- NOT this mutation's actual locus, see header note
muts[, Entrez_Gene_Id := 0]
muts[, Center := "."]
muts[, NCBI_Build := "NA"] # not a real genome build -- see header note on Chromosome/Start/End
muts[, Strand := "+"]
muts[, dbSNP_Val_Status := ""]
muts[, Match_Norm_Seq_Allele1 := ""]
muts[, Match_Norm_Seq_Allele2 := ""]
muts[, Mutation_Status := "Somatic"]
muts[, Sequencer := ""]

setnames(muts,
  old = c("tumour_sample_name", "germline_sample_name", "tumour_dp", "tumour_ref_dp", "tumour_alt_dp",
          "germline_dp", "germline_ref_dp", "germline_alt_dp", "vep_consequence", "vep_impact",
          "vep_feature", "vep_protein_position", "vep_codons", "vep_exon", "mutect_filter",
          "called_by_mutect", "chrom", "pos"),
  new = c("Tumor_Sample_Barcode", "Matched_Norm_Sample_Barcode", "t_depth", "t_ref_count", "t_alt_count",
          "n_depth", "n_ref_count", "n_alt_count", "Consequence", "IMPACT",
          "Transcript_ID", "Protein_position", "Codons", "Exon_Number", "Filter",
          "Called_By_Mutect", "HLA_Allele", "HLA_Allele_Position")
)

out <- muts[, ..maf_cols]

fwrite(out, args$output_maf, sep = "\t", col.names = TRUE, na = "")

cat("Wrote", nrow(out), "mutation rows to", args$output_maf, "\n")
