## Lines commented out with `#!` are required for the module to run
## Lines commented out with `#?` can optionally be user-configured
## Lines commented out with `##` act as regular comments

lcr-modules:
    utils:
        inputs:
            bed: "__UPDATE__"

        options:
            bam_sort: ""
            bam_markdups: ""
            bam_index: "-b"

        conda_envs:
            samtools: "envs/samtools-1.9.yaml"
            sambamba: "envs/sambamba-0.7.1.yaml"
            picard: "envs/picard-2.22.3.yaml"
            
        threads:
            bam_sort: 12
            bam_markdups: 12
            bam_index: 6
            interval: 2

        mem_mb:
            bam_sort: 12000
            bam_markdups: 8000
            bam_index: 4000
            interval: 4000

