## Lines commented out with `#!` are required for the module to run
## Lines commented out with `#?` can optionally be user-configured
## Lines commented out with `##` act as regular comments

lcr-modules:
    
    star:

        ## See main README.md for how to set `samples` in the Snakefile
        #! samples: null

        inputs:
            ## Available wildcards: {seq_type} {genome_build} {sample_id}
            #! sample_fastq_1: null
            #! sample_fastq_2: null

        ## See main README.md for how to set `reference` in the Snakefile
        #? reference:
        #?    genome_fasta: null

        ## List subdirectories that should be symlinked to the scratch directory
        scratch_subdirectories: []

        options:
            star: ""
            step_2: ""

        conda_envs:
            star: "{MODSDIR}/envs/star-2.7.3a.yaml"
            
        threads:
            star: 12

        mem_mb:
            star: 40000

        pairing_config:
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
