lcr-modules:
    
    hotmaps:

        inputs:
            # Available wildcards: {seq_type} {genome_build}
            input_maf: "__UPDATE__"
            sample_sets: "__UPDATE__"

        maf_processing:
            sample_sets: ["__UPDATE__"]
            seq_types: ["genome","capture"]
            include_non_coding: False
            prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.0/generate_smg_inputs.R"
            blacklists: ["/projects/rmorin_scratch/BL_DLBCL-BL-like_DLBCL_hotspot_analysis/blacklists/blacklist.grch37.tsv", "/projects/rmorin/projects/gambl-repos/gambl-mcruz/etc/curated_blacklist/candidateblacklist.schmitz.grch37.tsv"]
        
        vcf2maf:
            vep_cache: "__UPDATE__"
            options: ""

        hotmaps_repo: "https://github.com/morinlab/HotMAPS/archive/refs/heads/master.zip"

        pdb_stucture_dirs:
            modbase_dir: "__UPDATE__"
            pdb_dir: "__UPDATE__"
            refseq_homology_dir: "%(modbase_dir)s/ModBase_H_sapiens_2013_refseq/models/model/"
            ensembl_homology_dir: "%(modbase_dir)s/H_sapiens_2013/models/"
            biological_assembly_dir: "%(pdb_dir)s/biounit/coordinates/all/"
            non_biological_assembly_dir: "%(pdb_dir)s/structures/all/pdb/"

        options:
            mysql:
                mysql_host: "__UPDATE__"
                mysql_user: "__UPDATE__"
                mysql_db: "__UPDATE__"
                mysql_passwd: "__UPDATE__"
            hotmaps:
                hypermut_threshold: "500"
                pdb_splits: 500
                group_func: "min"
                q_value: ".01"
                num_sims: 10000
                radius: 10
                stop_criteria: 200

        update_mysql_tbl_script: "{MODSDIR}/etc/mysql_update_tbl.py"
        detailed_hotspots_script: "{MODSDIR}/etc/detailed_hotspots.py"

        scratch_subdirectories: []

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            bcftools: "{MODSDIR}/envs/bcftools.yaml"
            hotmaps: "{MODSDIR}/envs/hotmaps.yaml"
            
        threads:
            hotmaps: 4

        resources:
            hotmaps: 
                mem_mb: 2000
            
        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
