lcr-modules:
    
    oncodriveclustl:

        dirs:
            _parent:

        inputs:
            samples:
            maf_path: # Leave blank if using sample subset

        scratch_subdirectories: [] # Recommended: mutect2

        options:
            mode: pathology  # pathology, samples, subset, maf           
            genome_build: "grch37"
            seq_type: ["genome","capture"]
            
            pathology: [["DLBCL","BL"],["FL","MCL","CLL"]]

            sample_metadata: 
            
            sample_subset:
            sample_subset_file: 

            sample_ids: #"test1,test2,test3"
            id_nickname: #"test_run"

            clustl: ''
            reference:
                grch37: "/projects/nhl_meta_analysis_scratch/gambl/ref_local/oncodrive/oncodrive_files/hg19/hg19.cds.tsv.gz -g hg19"
                hg38: "/projects/nhl_meta_analysis_scratch/gambl/ref_local/oncodrive/oncodrive_files/hg38/hg38.cds.tsv.gz -g hg38"
            #custom_blacklist:

        coding_sequence: True

        r_script: "/home/mcruz/lcr-modules/modules/oncodriveclustl/1.0.1/src/oncomeRge.R"


        conda_envs:
            r_env: "/home/mcruz/lcr-modules/modules/oncodriveclustl/1.0.1/envs/GAMBLR.yaml"
            clustl: "{MODSDIR}/envs/oncodriveclustl-1.1.3.yaml"
            
        threads:
            clustl: 4

        resources:
            clustl:
                mem_mb: 2000

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            capture:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
