lcr-modules:

    sv_repair:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_vcf: "results/gambl/manta-2.3/99-outputs/vcf/{seq_type}--{genome_build}/somaticSV/{tumour_id}--{normal_id}--{pair_status}.somaticSV.vcf"

        scratch_subdirectories: []

        options:
            window_size: 1000

        conda_envs:
            readR: "config/envs/r-env.yaml"
            vcftools: "config/envs/vcftools.yaml"
            sambamba: "src/lcr-modules/envs/sambamba/sambamba-0.7.1.yaml"
            samtools: "src/lcr-modules/envs/samtools/samtools-1.9.yaml"
            bedtools: "src/lcr-modules/envs/bedtools/bedtools-2.29.2.yaml"
            clustalo: "config/envs/clustalo.yaml"

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False