lcr-modules:
    
    cluster_sv:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {tumour_id} {normal_id}
            sample_bedpe: "__UPDATE__"
        
        options:
            cluster_sv_version: 1.0
            # by default cluster sv references is included in the CLusterSV github repo
            # user can change this to use personalized references
            chr_sizes: null
            cen_telo_coords: null

        conda_envs:
            cluster_sv: "{MODSDIR}/envs/r-cluster_sv.yaml"
            
        threads:
            cluster_sv: 4

        mem_mb:
            cluster_sv: 2000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
