lcr-modules:

    combine_cnv:
        inputs:
            names: ["__UPDATE__"]
            sample_seg: ["__UPDATE__"]
        
        projections: ["__UPDATE__"]

        scratch_subdirectories: []

        conda_envs:
            CNVfilteR: "{MODSDIR}/envs/CNVfilteR.yaml"
            fill_segments: "{SCRIPTSDIR}/fill_segments/1.0/fill_segments.yaml"
            liftover-366: "{REPODIR}/modules/liftover/1.2/envs/liftover-366.yaml"

        options:
            concatenate_segs: "{MODSDIR}/src/bash/concatenate.sh"
            seg2bed2seg: "{REPODIR}/modules/liftover/1.2/src/convert_for_liftover.py"
            min_mismatch: 0.75

        threads:
            combine_cnv: 4

        resources:
            combine_cnv:
                mem_mb: 12000
                disk_mb: 1000 # Will ensure at least this much space is left

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
