lcr-modules:

    combine_cnv:
        # comma-separated list of modules used to call CNV
        # this order will also determine the preference which module's output will be used when multiple outputs are available
        # example: ["battenberg", "sequenza", "cnvkit", "controlfreec"]
        names: ["__UPDATE__", "__UPDATE__", ..., "__UPDATE__"]
        # comma-separated list of path to the location of seg files
        # must be in the same order as the names of the tools in previous key
        # supported wildcards are seq_type, tumour_id, normal_id, pair_status, tool, projection
        # example: ['results/battenberg-1.2/99-outputs/seg/{seq_type}--projection/{tumour_id}--{normal_id}--{pair_status}.{tool}.{projection}.seg',
        #    'results/sequenza-1.4/99-outputs/seg/{seq_type}--projection/{tumour_id}--{normal_id}--{pair_status}.{tool}.{projection}.seg',
        #    'results/cnvkit-1.0/99-outputs/seg/{seq_type}--projection/{tumour_id}--{normal_id}--{pair_status}.{tool}.{projection}.seg',
        #    'results/controlfreec-1.2/99-outputs/seg/{seq_type}--projection/{tumour_id}--{normal_id}--{pair_status}.{tool}.{projection}.seg'
        #    ]
        seg: ["__UPDATE__",
            "__UPDATE__",
            ...,
            "__UPDATE__"
            ]
        # requested projections of the merged files
        projections: ["grch37", "hg38"]

        scratch_subdirectories: []

        conda_envs:
            R: "{SCRIPTSDIR}/salmon2counts/1.0/salmon2counts.yaml"

        threads:
            combine_cnv: 4

        resources:
            combine_cnv:
                mem_mb: 12000
                disk_mb: 1000 # Will ensure at least this much space is left

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
