lcr-modules:
    
    stringtie_run:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            XS_script: "{MODSDIR}/src/tagXSstrandedData.awk"

        options:
            stringtie_run: ""
        
        conda_envs:
            stringtie: "{MODSDIR}/envs/stringtie.yaml"
            
        threads: 
            stringtie_run: 16

        resources:
            step_1: 
                mem_mb: 15000
            
        pairing_config:
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
