lcr-modules:
    
    mixcr:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_fastq_1: "__UPDATE__" 
            sample_fastq_2: "__UPDATE__"

        scratch_subdirectories: []

        options:
            mixcr_run: 
                mrna:
                    --starting-material rna
                genome:
                    --starting-material dna

        # TODO: Add the conda environment once MiXCR is available again - using the jar for now.
        conda_envs:
            mixcr: "{MODSDIR}/envs/mixcr"
            
        threads:
            mixcr_run: 4

        mem_mb:
            mixcr_run: 2000

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
