lcr-modules:
    
    mixcr:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_fastq_1: "__UPDATE__" 
            sample_fastq_2: "__UPDATE__"
            mixcr_exec: "{MODSDIR}/envs/mixcr"

        scratch_subdirectories: []

        options:
            mixcr_run: 
                mrna:
                    --starting-material rna
                genome:
                    --starting-material dna
            
        threads:
            mixcr_run: 4

        mem_mb:
            mixcr_run: 5300

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
