lcr-modules:

    fishhook:
        inputs:
            # Available wildcards: {seq_type}
            master_maf: "__UPDATE__"
            subsetting_categories: "__UPDATE__" # e.g. "data/metadata/level3_subsetting_categories.tsv"
        sample_set: ["__UPDATE__"] # E.g. ["DLBCL-only", "BL_DLBCL-BL-like_all"]
        # Uncomment the following line to add a launch_date. Otherwise the current year-month will be used
        # launch_date: ""

        include_non_coding: True
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.1/generate_smg_inputs.R"
        src_dir: "{MODSDIR}/src/"

        options:
            include_silent_mutation: False # Include silent mutations in maf file
            tiles_size: 1000 # This is the size of tiles you want to split the genome into, leave as "" if you want to use a gene list as hypothese
            target_gene_list: False # If you do not provide a tile size, please provide True here to used the mskilab provided file instead, gencode.v19.genes.gtf
            target_gene_list_only_protein_coding: True # Only include protein coding genes in gene list
            covariates:
                chrom_hmm: "/projects/dscott_prj/CCSRI_1500/exomes/ref/resources/E032_primaryBcells_fromPB_chromHMM_15state_segments.bed"
                rep_timing: "/projects/dscott_prj/CCSRI_1500/exomes/ref/resources/RT_GM12878_Lymphocyte_Int90901931_hg19.bedgraph.gz"

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            fishhook: "{MODSDIR}/envs/fishhook.yaml"

        threads:
            fishhook: 1

        resources:
            fishhook:
                mem_mb: 16000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
