lcr-modules:

    dnds:

        inputs:
            # Available wildcards: {seq_type}
            master_maf: "__UPDATE__"
            sample_sets: "__UPDATE__"
        sample_set: ["__UPDATE__"]
        seq_types: ["genome", "capture"]
        include_non_coding: True
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.0/generate_smg_inputs.R"
        src_dir: "{MODSDIR}/src/"

        options:
            step_1: ""
            step_2: ""

        conda_envs:
            samtools: "{MODSDIR}/envs/dnds.yaml"

        threads:
            step_1: 4

        resources:
            step_1:
                mem_mb: 2000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
