

#'
#' processing phyloWGS outputs pipeline that takes output json files and preprocessing output files
#' SAMPLE_ID.mutass.zip file must be unzipped before runing the script

#E example: how to run 
#mkdir -p output
#Rscript ./process.R --samplename SAMPLE_ID -j SAMPLE_ID.summ.json -t unziped.mutass/ -s ssm_data.txt -c cnv_data.txt -a SAMPLE_ID--matched_slms-3.final_deblacklisted_augmented.maf -b SAMPLE_ID_matched_slms-3.final_deblacklisted_augmented.maf -m SAMPLE_ID.muts.json -o out

##################################################
# load required libraries
##################################################

library("optparse")
library("rjson")
library("plyr")
require("dplyr")
require("ggplot2")
library("tidyr")


##################################################
# Command line options
##################################################

option_list = list(
  make_option(c("-n", "--samplename"), type="character", default=NULL, help="Samplename of the sample to run", metavar="character"),
  make_option(c("-j", "--json_summ"), type="character", default=NULL, help="SAMPLE_ID.summ.json file generated by phyloWGS", metavar="character"),
  make_option(c("-t", "--trees_out"), type="character", default=NULL, help="Directory containing unzipped XX.mutass.zip trees", metavar="character"),
  make_option(c("-s", "--ssm"), type="character", default=NULL, help="Preprocessing ssm_data.txt output file", metavar="character"),
  make_option(c("-c", "--copynumber"), type="character", default=NULL, help="Preprocessing cnv_data.txt output file", metavar="character"),
  make_option(c("-a", "--tumourA_maf"), type="character", default=NULL, help="Agument maf file of tumour A", metavar="character"),
  make_option(c("-b", "--tumourB_maf"), type="character", default=NULL, help="Agument maf file of tumour B", metavar="character"),
  make_option(c("-m", "--json_muts"), type="character", default=NULL, help="SAMPLE_ID.muts.json file", metavar="character"),
  make_option(c("-o", "--output"), type="character", default=NULL, help="Output directory", metavar="character")
)

opt_parser = OptionParser(option_list=option_list)
opt = parse_args(opt_parser)

samplename = opt$samplename
json_file = opt$json_summ
trees_out= opt$trees_out   ###  directory where unziped SAMPLE_ID.mutass.zip trees are
ssm_file = opt$ssm
cnv_file = opt$copynumber
mafA = opt$tumourA_maf
mafB = opt$tumourB_maf
mut_file = opt$json_muts
output_dir = opt$output



.checkfile = function(infile) {
  
  if (!file.exists(infile)) {
    
    stop(paste("File", infile, "does not exist", sep=""))
    
  }
  
}


.checkfile(json_file)
.checkfile(ssm_file)
.checkfile(cnv_file)
.checkfile(mafA)
.checkfile(mafB)
.checkfile(mut_file)

##################################################
# Process input files
###################################################
# Parse the input file and obtain the required data for this run
result1 <- fromJSON(file = json_file)
result_mut<-fromJSON(file = mut_file)
ssm_pre<-read.table(file = ssm_file, header = TRUE)
cnv_pre<-read.delim(file = cnv_file, header = TRUE)[,c("cnv","a","d")]
maf_TA<-read.delim(file = mafA, header = TRUE)
maf_TB<-read.delim(file = mafB, header = TRUE)


##################################################
# define output files
##################################################
out_json_to_Rtable= file.path(output_dir, paste("out_res_",samplename,"_json_converted_toR.table", sep = ""))
ssm_to_trees= file.path(output_dir, paste("out_res_",samplename,"_assigned_ssms_to_best_tree_maf_format.table", sep = ""))
cnv_to_trees= file.path(output_dir, paste("out_res_",samplename,"_assigned_cnvs_to_best_tree_maf_format.table", sep = ""))
cellular_prevalence_plot= file.path(output_dir, paste("cellular_prevalence_",samplename,".pdf", sep = ""))
CCF_plot= file.path(output_dir, paste("cancer_cell_fraction_",samplename,".pdf", sep = ""))
VAF_plot= file.path(output_dir, paste("vaf_",samplename,".pdf", sep = ""))
VAF_coding_plot= file.path(output_dir, paste("vaf_ccoding",samplename,".pdf", sep = ""))


###################################################
# open summ.json file and convert it into humam readable format
###################################################

#this function opens SAMPLE_ID_summ.jason and converts it into R table
open_tree = function(json_summ_file,out_json_to_Rtable){

  out_res<-NULL
  for (j in 1:length(json_summ_file[["trees"]])){
  
  tree_focal<-json_summ_file[["trees"]][j]
  tree_focal_statA<-as.data.frame(t(unlist(sapply(tree_focal,function(x)x[c("clustering_index","branching_index","llh","linearity_index")])))) 
  colnames(tree_focal_statA)<-c("clustering_index","branching_index","llh","linearity_index")
  tree_focal_statA$tree_id<-j-1
  rownames(tree_focal_statA)<-NULL
  
  
  tree_focal_statB<-as.data.frame(sapply(tree_focal,function(x)x[3]))[1,-c(3,6,9,12,15,18,21,24,27,30)]
  #tree_focal_statB<-as.data.frame(sapply(tree_focal,function(x)x[3]))[1,!(grepl("cellular_prevalence",colnames(tree_focal_statB)))]
  colnames(tree_focal_statB)<-sub("^[^.]*.", "", colnames(tree_focal_statB))
  stat_both<-cbind(tree_focal_statA,tree_focal_statB)
  out_res<-rbind.fill(stat_both,out_res)  
  out_res_ordered<-out_res[order(out_res$tree_id),] 
  } # for j loop 

density<-json_summ_file["tree_densities"]
density_unlist<-data.frame("density"=unlist(density))
row.names(density_unlist)<-sub("^[^.]*.", "", row.names(density_unlist))

density_unlist$tree_id<-row.names(density_unlist)
row.names(density_unlist)<-NULL

final_table=merge(out_res_ordered,density_unlist, by.x = "tree_id", by.y = "tree_id")   ## add tree densities to all tress table
write.table(final_table, file =out_json_to_Rtable ,col.names = TRUE, row.names = FALSE, sep = "\t",quote = FALSE)
return(final_table)
}


result_tree<-open_tree(result1,out_json_to_Rtable)


###################################################
# extrcats the best tree
###################################################
#the best tree is the tree with the highest density

best_tree_id = function(R_table, density) {
  best=R_table[which.max(R_table$density),]
  best_tree_focal_name<-best$tree_id
  best_tree_id<-paste(best$tree_id,"json",sep = ".")
  return(best_tree_id)
  return(best_tree_focal_name)
}
best_tree_fileID<-best_tree_id(result_tree, density)


#######################################################################
# extract the stats (SNvs and CNVs assigned to each population) from the best tree 
#######################################################################

open_best_tree = function(trees_out,best_tree_id){
	rr <- fromJSON(file = paste(trees_out,best_tree_id, sep = "/")) 
	return(rr)
}
rr= open_best_tree(trees_out,best_tree_fileID)


#######################################################################
# annotate point mutations and CNVs in the best tree
#######################################################################
best_focal<-result1[["trees"]][as.numeric(gsub(".json","",best_tree_fileID))+1]
tree_structure<-as.data.frame(sapply(best_focal,function(x)x["structure"]))  ##[6]


merge_both<-function(result1,best_tree_fileID,tree_structure){
best_tree<-as.numeric(gsub(".json","",best_tree_fileID))
best_focal<-result1[["trees"]][best_tree+1]
tree_focal_statB<-as.data.frame(sapply(best_focal,function(x)x["populations"]))   ##[3]
qq<-tree_focal_statB[,grep("cellular_prevalence",colnames(tree_focal_statB))]

sample1<-data.frame(t(qq[1,]))
sample1$sample_id<-rep("TumourA")
sample1$population<-row.names(sample1)
row.names(sample1)<-NULL
colnames(sample1)<-c("cellular_prevalence","sample_id","population")
sample1$population<-sub(".*?\\.(.*?\\..*?)\\..*", "\\1", sample1$population)
sample1<-sample1[!(sample1$population=="populations.0"),]

  if (length(unique(tree_structure[,grep("structure.0",names(tree_structure))]))==1){
  sample1$CCF<-(sample1$cellular_prevalence/(max(sample1$cellular_prevalence)))
  }  
  if (length(unique(tree_structure[,grep("structure.0",names(tree_structure))]))==2){
  sample1$CCF<-(sample1$cellular_prevalence/((max(sample1$cellular_prevalence))+(sort(sample1$cellular_prevalence)[length(sample1$cellular_prevalence)-1])))
  } 
  if (length(unique(tree_structure[,grep("structure.0",names(tree_structure))]))==3){
  sample1$CCF<-(sample1$cellular_prevalence/((max(sample1$cellular_prevalence))+(sort(sample1$cellular_prevalence)[length(sample1$cellular_prevalence)-1])+(sort(sample1$cellular_prevalence)  [length(sample1$cellular_prevalence)-2])))
 }


sample2<-data.frame(t(qq[2,]))
sample2$sample_id<-rep("TumourB")
sample2$population<-row.names(sample2)
row.names(sample2)<-NULL
colnames(sample2)<-c("cellular_prevalence","sample_id","population")
sample2$population<-sub(".*?\\.(.*?\\..*?)\\..*", "\\1", sample2$population)
sample2<-sample2[!(sample2$population=="populations.0"),]


  if (length(unique(tree_structure[,grep("structure.0",names(tree_structure))]))==1){
  sample2$CCF<-(sample2$cellular_prevalence/(max(sample2$cellular_prevalence)))
  }  
  if (length(unique(tree_structure[,grep("structure.0",names(tree_structure))]))==2){
  sample2$CCF<-(sample2$cellular_prevalence/((max(sample2$cellular_prevalence))+(sort(sample2$cellular_prevalence)[length(sample2$cellular_prevalence)-1])))
  } 
  if (length(unique(tree_structure[,grep("structure.0",names(tree_structure))]))==3){
  sample2$CCF<-(sample2$cellular_prevalence/((max(sample2$cellular_prevalence))+(sort(sample2$cellular_prevalence)[length(sample2$cellular_prevalence)-1])+(sort(sample2$cellular_prevalence) [length(sample2$cellular_prevalence)-2])))
  }


both_samples<-rbind(sample1,sample2)
both_samples$best_tree_ID<-rep(best_tree)
both_samples<-both_samples[!(both_samples$population=="populations.0"),]

}

both_samples<-merge_both(result1,best_tree_fileID,tree_structure)



ssm = function(stat_best_tree, ssm_pre,ssm_to_trees,tree_structure){
  
  out_res_ssm<-NULL
  for ( i in 1:length(stat_best_tree$mut_assignments)){
    focal<-(stat_best_tree$mut_assignments)[i]
  
   focal_ssms<-data.frame(sapply(focal, function(x) x[1]))
   	
   	colnames(focal_ssms)<-sub("^[^.]*.", "", colnames(focal_ssms))
   focal_ssms$populations_ssms<-paste("population",i, sep = "_")
   ssm_assign<-merge(ssm_pre,focal_ssms, by.x = "id", by.y = "ssms")[,c("id", "gene","populations_ssms")]
   ssm_assign_spi<-separate(ssm_assign, col = gene, into = c("Chromosome","Start_Position"), sep = "_")
   ssm_assign_with_maf<- merge(ssm_assign_spi, maf_TA, by.x=c("Chromosome","Start_Position"), by.y=c("Chromosome","Start_Position"))
   out_res_ssm<-rbind(ssm_assign_with_maf,out_res_ssm)    
   	
   } ## i loop 
  
   
   #return(out_res_ssm)
  
       out_res_clonality<-NULL
       for (pp in 1:nrow(out_res_ssm)){
       focal_structure<-data.frame("yy"=unique(tree_structure[,grep("structure.0",names(tree_structure))]))
       focal_row<-out_res_ssm[pp,]
       if (gsub("population_","",focal_row$populations)%in%(focal_structure$yy)){
       focal_row$clonal_status<-"clonal"
    
       } else {
       focal_row$clonal_status<-"subclonal"
    }
   
  out_res_clonality<-rbind(out_res_clonality,focal_row)

 } ## pp loop 
    write.table(out_res_clonality, file =ssm_to_trees ,col.names = TRUE, row.names = FALSE, sep = "\t",quote = FALSE)

   return(out_res_clonality)
}

ss<-ssm(rr,ssm_pre,ssm_to_trees,tree_structure)


###########################################################
## load mut file to extrcat CNVs start and end positions
###########################################################

cnv = function(stat_best_tree, cnv_pre,mutation_file,cnv_to_trees){
  out_res_cnv<-NULL
  for ( ii in 1:length(stat_best_tree$mut_assignments)){     ## ii loop assigns populations to CNVs
  focal_cnvs_l<-(stat_best_tree$mut_assignments)[ii]
  
  focal_cnvs<-data.frame(sapply(focal_cnvs_l, function(x) x[2]))
  colnames(focal_cnvs)<-sub("^[^.]*.", "", colnames(focal_cnvs))
  focal_cnvs$populations_cnvs<-paste("population",ii, sep = "_")
  out_res_cnv<-rbind.fill(focal_cnvs,out_res_cnv)
  
  } ## ii loop 
  
  #return(out_res_cnv)
      out_res_mut<-NULL
      for (cn in 1:length(result_mut$cnvs)){
      focal_mut_cnv<-(result_mut$cnvs)[cn]
  
      focal_mut<-data.frame(sapply(focal_mut_cnv, function(x) x[1]))[1,]
      colnames(focal_mut)<-sub("^[^.]*.", "", colnames(focal_mut))
      focal_mut$cnv_id<-names(focal_mut_cnv)
      out_res_mut<-rbind.fill(focal_mut,out_res_mut)
      } ## cn loop
  
    both_cnvs<-merge(out_res_cnv, out_res_mut, by.x = "cnvs",by.y = "cnv_id")  
    write.table(both_cnvs, file =cnv_to_trees ,col.names = TRUE, row.names = FALSE, sep = "\t",quote = FALSE)
  
}


cnv<-cnv(rr, cnv_pre,result_mut,cnv_to_trees)


##################### plot the results ####################
###########################################################
#### Slope chart the best tree, cellular prevalence #######

plot_cp<-function(both_samples,cellular_prevalence_plot){
pdf(cellular_prevalence_plot, width = 8, height =8 )
plotA<-ggplot(data = both_samples, aes(x = sample_id, y = cellular_prevalence, group = population)) +
  geom_line(aes(color = population), size = 2) +
  labs(title = paste("Best Tree",gsub(".json", "",best_tree_fileID), sep = " "))+  
  geom_point(aes(color = population), size = 4) +
  #  Labelling as desired
  xlab("Sample") + ylab("Cellular prevalence")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill = NA, colour = NA, size = 0.25),axis.text=element_text(size=16),axis.title=element_text(size=18),
        plot.margin = margin(1, 1., 1, 1.5, "cm"),axis.title.y = element_text(margin = margin(t = 70, r = 20, b = 50, l = 10)))
print(plotA)
dev.off() 
}

plot_cp(both_samples,cellular_prevalence_plot)

###########################################################
#### Slope chart the best tree, CCF #######

plot_cp<-function(both_samples,CCF_plot){
pdf(CCF_plot, width = 8, height =8 )
plotB<-ggplot(data = both_samples, aes(x = sample_id, y = CCF, group = population)) +
  geom_line(aes(color = population), size = 2) +
  labs(title = paste("Best Tree",gsub(".json", "",best_tree_fileID), sep = " "))+  
  geom_point(aes(color = population), size = 4) +
  #  Labelling as desired
  xlab("Sample") + ylab("CCF")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill = NA, colour = NA, size = 0.25),axis.text=element_text(size=16),axis.title=element_text(size=18),
        plot.margin = margin(1, 1., 1, 1.5, "cm"),axis.title.y = element_text(margin = margin(t = 70, r = 20, b = 50, l = 10)))
print(plotB)
dev.off() 
}

plot_cp(both_samples,CCF_plot)


#############################################
##### Slope chart the best tree (VAF) #######

maf_TA$VAF<-(maf_TA$t_alt_count/maf_TA$t_depth)
maf_TA$tumour_type<-rep("TumourA")
TA = merge(ss[,c("Chromosome","Start_Position","id", "populations_ssms")], maf_TA, by.x = c("Chromosome","Start_Position"),by.y=c("Chromosome","Start_Position"))


maf_TB$VAF<-(maf_TB$t_alt_count/maf_TB$t_depth)
maf_TB$tumour_type<-rep("TumourB")
TB = merge(ss[,c("Chromosome","Start_Position","id", "populations_ssms")], maf_TB, by.x = c("Chromosome","Start_Position"),by.y=c("Chromosome","Start_Position"))

both_Ts<-rbind(TA,TB)
both_Ts$populations_ssms<-gsub("_","",both_Ts$populations_ssms)
colnames(both_Ts)[4]<-"populations"


plot_vaf<-function(both_Ts,VAF_plot){
pdf(VAF_plot, width = 8, height =8 )
plotC<-ggplot (data =both_Ts , aes(x = tumour_type, y = VAF, group = interaction(populations, Start_Position) ,color = populations)) + 
  geom_line(aes(color = populations), size=0.2, alpha=0.4)+
  labs(title = paste("Best Tree",gsub(".json", "",best_tree_fileID), sep = " "))+  
  xlab("Sample") + ylab("VAF") +
  guides(colour = guide_legend(override.aes = list(alpha = 3)))+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill = NA, colour = NA, size = 2),axis.text=element_text(size=16),axis.title=element_text(size=18),
        plot.margin = margin(1, 1., 1, 1.5, "cm"),axis.title.y = element_text(margin = margin(t = 70, r = 20, b = 50, l = 10)))
print(plotC)
dev.off() 
}
 
plot_vaf(both_Ts,VAF_plot)

#############################################################
##### Slope chart the best tree (VAF, coding regions, nonsense, missense and splicing sites) #######

both_Ts_coding<-both_Ts[(both_Ts$Variant_Classification == "Missense_Mutation"| both_Ts$Variant_Classification =="Nonsense_Mutation"|both_Ts$Variant_Classification =="Splice_Site"),]

plot_vaf_coding<-function(vaf_coding,VAF_coding_plot){

pdf(VAF_coding_plot, width = 8, height =8 )
plotD<-ggplot (data =both_Ts_coding , aes(x = tumour_type, y = VAF, group = interaction(populations, Start_Position) ,color = populations)) + 
  geom_line(aes(color = populations), size=0.7, alpha=0.8)+
  labs(title = paste("Best Tree",gsub(".json", "",best_tree_fileID), sep = " "))+ 
  geom_text(data = both_Ts_coding %>% filter(tumour_type == "TumourB"), 
            aes(label = Hugo_Symbol) , 
            hjust = -0.3, 
            size = 2) +
            xlab("Sample") + ylab("VAF") +
            guides(colour = guide_legend(override.aes = list(alpha = 3)))+
            theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            panel.background = element_blank(), axis.line = element_line(colour = "black"),
            legend.key = element_rect(fill = NA, colour = NA, size = 2),axis.text=element_text(size=16),axis.title=element_text(size=18),
            plot.margin = margin(1, 1., 1, 1.5, "cm"),axis.title.y = element_text(margin = margin(t = 70, r = 20, b = 50, l = 10)))

print(plotD)
dev.off() 
}  


plot_vaf_coding(both_Ts_coding,VAF_coding_plot)
 

############
##### END ##
############




