lcr-modules:
    
    mutect2:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"

        scratch_subdirectories: []

        options:
            mutect2_run: ""
            mutect2_filter: ""

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            gatk: "{MODSIR}/envs/gatk-4.1.8.1.yaml"
            
        threads:
            mutect2_run: 1
            mutect2_filter: 1

        mem_mb:
            mutect2_run: 10000
            mutect2_filter: 512

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
