lcr-modules:
    
    battenberg:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
            battenberg_script: "{MODSDIR}/src/R/battenberg_wgs_hg38.R"
            calc_sex_status: "{MODSDIR}/src/bash/calc_sex_status.sh"
            cnv2igv: "{SCRIPTSDIR}/cnv2igv/1.0/cnv2igv.py"

        scratch_subdirectories: []

        reference_path:
            hg38: "/projects/rmorin_scratch/reference/battenberg_hg38" #UPDATE
            grch37: "/projects/rmorin/reference/battenberg" #UPDATE

        options:
            chr_prefixed_reference:
                hg38: " --chr_prefixed_genome "
                grch37: " "
            x_chrom: 
                grch37: "X"
                hg38: "chrX"
            y_chrom: 
                grch37: "Y" 
                hg38: "chrY"

        conda_envs:
            battenberg: "{MODSDIR}/envs/battenberg_fresh.yml"
            
        threads:
            battenberg: 24

        mem_mb:
            battenberg: 200000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
