lcr-modules:
    
    bam2fastq:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"

        options:
            bam2fastq: "VALIDATION_STRINGENCY=LENIENT"

        conda_envs:
            picard: "{MODSDIR}/envs/picard-2.22.3.yaml"
            
        threads:
            bam2fastq: 4

        mem_mb:
            bam2fastq: 5000

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            capture:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
