## Lines commented out with `#!` are required for the module to run
## Lines commented out with `#?` can optionally be user-configured
## Lines commented out with `##` act as regular comments

lcr-modules:
    
    utils:

        ## See main README.md for how to set `samples` in the Snakefile
        #! samples: null

        inputs:
            ## Available wildcards: {seq_type} {genome_build} {sample_id}
            #! sample_fastq: null

        ## See main README.md for how to set `reference` in the Snakefile
        #? reference:
        #?    genome_fasta: null

        ## List subdirectories that should be symlinked to the scratch directory
        scratch_subdirectories: []

        options:
            bam_sort: null
            bam_markdups: null
            bam_index: null

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            sambamba: "{MODSDIR}/envs/sambamba-0.7.1.yaml"
            
        threads:
            bam_sort: null
            bam_mdups: null
            bam_index: null

        mem_mb:
            bam_sort: 12000
            bam_mdups: 8000
            bam_index: 4000
            
        pairing_config:
