lcr-modules:

    _shared:
        lcr-modules: "../"
        lcr-scripts: "../../lcr-scripts"
        root_output_dir: "results/"
        scratch_directory: "scratch/"
        pairing_config:
            capture:
                unmatched_normal_id: "TCRBOA7-N-WEX"

    star:
        inputs:
            sample_fastq_1: "data/{sample_id}.read1.fastq.gz"
            sample_fastq_2: "data/{sample_id}.read2.fastq.gz"
        reference_params:
            star_overhang: "99"
        scratch_subdirectories: ["star", "sort_bam", "mark_dups"]

    manta:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"

    utils:
        inputs:
            bed: 
                grch37: "reference/exomes/grch37/bed/{id}.bed" # make sure this corresponds with config["lcr-modules"]["picard_qc"]["inputs"]["intervals"]
            
    picard_qc:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
            # add other genomes
            intervals: 
            # if using one kit per genome build, use _default key
                grch37: 
                    _default: "reference/exomes/grch37/interval/S07604624_intervals.txt"
            # if using more that one kit per genome build, use kit id as key and set _default to null/empty string
            # grch37: 
            #        _default: null
            #        S07604624: "reference/exomes/grch37/interval/S07604624_intervals.txt"
            #        kit_2: "reference/exomes/grch37/interval/kit_2_intervals.txt"
