lcr-modules:

    _shared:
        lcr-modules: "../"
        lcr-scripts: "../../lcr-scripts/"
        root_output_dir: "results/"
        scratch_directory: "scratch/"
        unmatched_normal_ids:
            capture--grch37: "TCRBOA7-N-WEX"
            genome--hg38: "BLGSP-71-23-00361-14A-01E"

    slms_3: 
        inputs: 
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"


    bam2fastq:
        inputs:
            sample_bam: "data/{sample_id}.bam"
        temp_outputs: False # fastq outputs will be temporary

    star:
        inputs:
            sample_fastq_1: "results/bam2fastq-1.2/99-outputs/{seq_type}/{sample_id}.read1.fastq.gz"
            sample_fastq_2: "results/bam2fastq-1.2/99-outputs/{seq_type}/{sample_id}.read2.fastq.gz"
        scratch_subdirectories: []

    manta:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
   
    mixcr:
        inputs:
            sample_fastq_1: "data/{sample_id}.read1.fastq.gz"
            sample_fastq_2: "data/{sample_id}.read2.fastq.gz"

    vcf2maf:
        dirs:
            _parent: "results/sage-1.0_vcf2maf-1.2"
        inputs:
            vep_cache: "reference/vep_caches/"
            sample_vcf_gz: "results/sage-1.0/99-outputs/combined/{seq_type}--{genome_build}/{tumour_id}--{normal_id}--{pair_status}.{base_name}.vcf.gz"
            convert_coord: "{SCRIPTSDIR}/crossmap/1.0/convert_maf_coords.sh"
        vcf_base_name: "sage.combined"
        options:
            vcf2maf: "--filter-vcf 0 --vcf-tumor-id {tumour_id} --vcf-normal-id {normal_id}"
            species: "homo_sapiens"
        conda_envs:
            vcf2maf: "{MODSDIR}/envs/vcf2maf-1.6.18.yaml"
            crossmap: "{SCRIPTSDIR}/crossmap/1.0/convert_maf_coords.yaml"
        # here you can specify path to txt file with a list of custom ENST IDs that override canonical selection
        # it will be parsed to --custom-enst flag of vcf2maf
        # if no non-canonical transcript IDs to be included, leave switches empty
        # This is just an example of how to include the list of custom IDs
        switches:
            custom_enst:
              hg38: ""
              grch37: "data/custom_enst.txt"
              hs37d5: ""
        resources:
            vcf2maf:
                mem_mb: 12000
                vcf: 1
            crossmap:
                mem_mb: 12000


    salmon:
        inputs:
            sample_fastq_1: "data/{sample_id}.read1.fastq.gz"
            sample_fastq_2: "data/{sample_id}.read2.fastq.gz"
        transcriptome:
            quant_to: "hg38"

    sequenza:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
        scratch_subdirectories: []
    
    lofreq:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
            lofreq_filter: "{MODSDIR}/src/bash/lofreq_filter.sh"
        switches:
            # Intentionally running LoFreq without a BED file for simplicity
            # And to avoid having to include a large BED file in the repo
            regions_bed:
                _default: ""
                capture: ""

    gridss: 
        inputs: 
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
        references: 
            # See the current gridss module config file for details about where to obtain this file. 
            viral_fa: "/projects/rmorin/projects/DLBCL_DHITsig_genomes/reference/gridss/refgenomes/human_virus/human_virus.fa"
            viral_bwa_prefix: "/projects/rmorin/projects/DLBCL_DHITsig_genomes/reference/gridss/refgenomes/human_virus/human_virus.fa"
            pon_dir: "/projects/rmorin/reference/hmftools-references/gridss/pon"
            
    strelka:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
            # if using manta output, use vcf file in the 99-outputs subdirectory and ensure manta version corresponds to the loaded module
            candidate_small_indels: "results/manta-2.3/99-outputs/vcf/{seq_type}--{genome_build}/candidateSmallIndels/{tumour_id}--{normal_id}--{pair_status}.candidateSmallIndels.vcf"

    utils:
        inputs:
            bed: 
                grch37: "data/exome_bed/hg19/target_regions.nochr.bed" # make sure this corresponds with config["lcr-modules"]["picard_qc"]["inputs"]["intervals"]
                # if testing on GSC, use this file: "/projects/dscott_prj/CCSRI_1500/exomes/ref/agilent/hg19/target_regions.nochr.bed"
        mem_mb:
            bam_sort: 48000
        threads:
            bam_sort: 12

    picard_qc:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
        switches:
            capture_intervals: 
                _default: "reference/exomes/grch37/interval/target_regions.nochr_intervals.txt"
                # if 'capture_kit_id' is a column in samples.tsv and contain more than one kit_id, specify each kit using the values in the column. e.g. and add the corresponding bed file if needed
                # S07604624: "reference/exomes/grch37/interval/S07604624_intervals.txt"
                # <grch38_kit>: "reference/exomes/grch38/interval/<grch38_kit>_intervals.txt"
    
    bwa_mem:
        inputs:
            sample_fastq_1: "results/bam2fastq-1.2/99-outputs/{seq_type}/{sample_id}.read1.fastq.gz"
            sample_fastq_2: "results/bam2fastq-1.2/99-outputs/{seq_type}/{sample_id}.read2.fastq.gz"
        scratch_subdirectories: []
        
    controlfreec:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
            
    liftover:
        tool: "battenberg"
        inputs:
            sample_seg: "data/{tool}/hg38/{tumour_sample_id}--{normal_sample_id}_subclones.igv.seg"
    
    ichorcna:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"
            
        scratch_subdirectories: [] # mpileup should be in scratch space

    starfish: 
        dirs: 
            _parent: "results/starfish-2.0_strelka-1.1_lofreq-1.0"
        inputs: 
            names: ["strelka", "lofreq"]
            paths: 
                [
                    "results/strelka-1.1/99-outputs/vcf/{seq_type}--{genome_build}/{tumour_id}--{normal_id}--{pair_status}.strelka.combined.vcf.gz", 
                    "results/lofreq-1.0/99-outputs/{seq_type}--{genome_build}/{tumour_id}--{normal_id}--{pair_status}.lofreq.snvs.vcf.gz"
                ]

    sage:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "data/{sample_id}.bam"

        # include here any additional flags to modify default parameters
        options:
            sage_run: ""
