lcr-modules:

    _shared:
        lcr-modules: "../"
        lcr-scripts: "../../lcr-scripts"
        root_output_dir: "results/"
        scratch_directory: "scratch/"
        pairing_config:
            capture:
                unmatched_normal_id: "TCRBOA7-N-WEX"

    star:
        inputs:
            sample_fastq_1: "data/{sample_id}.read1.fastq.gz"
            sample_fastq_2: "data/{sample_id}.read2.fastq.gz"
        reference_params:
            star_overhang: "99"
        scratch_subdirectories: ["star", "sort_bam", "mark_dups"]

    manta:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            sample_bai: "data/{sample_id}.bam.bai"

    utils:
        inputs:
            bed: "reference/exomes/grch37/bed/{id}.bed"
            
    picard_qc:
        inputs:
            sample_bam: "data/{sample_id}.bam"
            intervals: "reference/exomes/{genome_build}/interval/S07604624_intervals.txt"
