lcr-modules:
    _shared:
        # Typically, this will be something like "src/lcr-modules"
        repository: "../"
        # Typically, this will be something like "src/lcr-scripts"
        # The value here assumes `lcr-scripts` is alongside `lcr-modules`
        lcr-scripts: "../../lcr-scripts"
        # The modules will output in subdirectories of "results/"
        # For example: "results/manta-1.0/"
        root_output_dir: "results/"
        # This specifies where to output files that are ideally stored in
        # a scratch directory (e.g., large intermediate files)
        scratch_directory: "/projects/rmorin_scratch/my_project/"
        # This specifies the sample to use as a normal for unpaired tumours
        # (manta runs unpaired tumours with unmatched normal samples)
        pairing_config:
            genome:
                unmatched_normal_id: "BLGSP-71-06-00001-99A-01D"
