lcr-modules:

    _shared:
        lcr-modules: "../"
        lcr-scripts: "../../lcr-scripts"
        root_output_dir: "results/"
        scratch_directory: "scratch/"

    cellranger:
        inputs:
            sample_dir: "sc_data/"
        reference:
            transcriptome: "/projects/clc/references/cellranger/refdata-cellranger-GRCh38-3.0.0"
            vdj: "/projects/clc/references/cellranger/refdata-cellranger-vdj-GRCh38-alts-ensembl-3.1.0"
