#!/usr/bin/env snakemake


##### SETUP #####


import oncopipe as op

SAMPLES = op.load_samples("sc_data/samples.tsv")
SAMPLES["patient_id"] = SAMPLES["chip_id"]
SAMPLES["tissue_status"] = "tumour"
SAMPLES["genome_build"] = "grch38"

##### REFERENCE_FILES WORKFLOW #####


subworkflow reference_files:
    workdir:
        "reference/"
    snakefile:
        "../workflows/reference_files/2.3/reference_files.smk"
    configfile:
        "../workflows/reference_files/2.3/config/default.yaml"


##### CONFIGURATION FILES #####


# Load module-specific configuration
configfile: "../modules/cellranger/1.0/config/default.yaml"

# Load project-specific config, which includes the shared 
# configuration and some module-specific config updates
configfile: "config.yaml"


##### CONFIGURATION UPDATES #####


# Use all samples as a default sample list for each module
config["lcr-modules"]["_shared"]["samples"] = SAMPLES


##### MODULE SNAKEFILES #####


# Load module-specific snakefiles
include: "../modules/cellranger/1.0/cellranger.smk"


##### TARGETS ######


rule all:
    input:
        rules._cellranger_all.input
