#!/usr/bin/env snakemake


##### SETUP #####


import oncopipe as op

SAMPLES = op.load_samples("data/samples.tsv")


##### REFERENCE_FILES WORKFLOW #####


subworkflow reference_files:
    workdir:
        "reference/"
    snakefile:
        "../workflows/reference_files/2.4/reference_files.smk"
    configfile:
        "../workflows/reference_files/2.4/config/default.yaml"


##### CONFIGURATION FILES #####


# Load module-specific configuration
configfile: "../modules/salmon/1.0/config/default.yaml"
configfile: "../modules/bam2fastq/1.0/config/default.yaml"
configfile: "../modules/star/1.3/config/default.yaml"
configfile: "../modules/manta/2.3/config/default.yaml"
configfile: "../modules/vcf2maf/1.0/config/default.yaml"
configfile: "../modules/sequenza/1.4/config/default.yaml"
configfile: "../modules/strelka/1.1/config/default.yaml"
configfile: "../modules/utils/2.0/config/default.yaml"
configfile: "../modules/bwa_mem/1.0/config/default.yaml"
configfile: "../modules/liftover/1.1/config/default.yaml"
configfile: "../modules/controlfreec/1.1/config/default.yaml"


# Load project-specific config, which includes the shared 
# configuration and some module-specific config updates
configfile: "config.yaml"


##### CONFIGURATION UPDATES #####


# Use all samples as a default sample list for each module
config["lcr-modules"]["_shared"]["samples"] = SAMPLES


##### MODULE SNAKEFILES #####


# Load module-specific snakefiles
include: "../modules/salmon/1.0/salmon.smk"
include: "../modules/bam2fastq/1.0/bam2fastq.smk"
include: "../modules/star/1.3/star.smk"
include: "../modules/manta/2.3/manta.smk"
include: "../modules/vcf2maf/1.0/vcf2maf.smk"
include: "../modules/sequenza/1.4/sequenza.smk"
include: "../modules/strelka/1.1/strelka.smk"
include: "../modules/utils/2.0/utils.smk"
include: "../modules/bwa_mem/1.0/bwa_mem.smk"
include: "../modules/liftover/1.1/liftover.smk"
include: "../modules/controlfreec/1.1/controlfreec.smk"



##### TARGETS ######

rule all:
    input:
        rules._salmon_all.input,
        rules._bam2fastq_all.input,
        rules._star_all.input,
        rules._manta_all.input,
        rules._sequenza_all.input,
        rules._strelka_all.input,
        rules._bwa_mem_all.input,
        rules._liftover_all.input,
        rules._controlfreec_all.input
