#!/usr/bin/env snakemake


##### PACKAGES #####


# Load oncopipe package for convenience functions
import oncopipe as op


##### REFERENCE_FILES WORKFLOW #####


subworkflow reference_files:
    workdir:
        "reference/"
    snakefile:
        "../workflows/reference_files/1.0/reference_files.smk"
    configfile:
        "../workflows/reference_files/1.0/config/default.yaml"


##### CONFIGURATION FILES #####


# Load module-specific configuration
configfile: "../modules/star/1.0/config/default.yaml"
configfile: "../modules/manta/2.0/config/default.yaml"

# Load project-specific config (including "lcr-modules" section)
configfile: "config.yaml"


##### CONFIGURATION UPDATES #####


# Load samples using convenience function
SAMPLES = op.load_samples("data/samples.tsv")

# Use all samples as a default sample list for each module
config["lcr-modules"]["_shared"]["samples"] = SAMPLES


##### MODULE SNAKEFILES #####


# Load module-specific snakefiles
include: "../modules/star/1.0/star.smk"
include: "../modules/manta/2.0/manta.smk"


##### TARGETS ######

rule all:
    input:
        rules._manta_all.input,
        rules._star_all.input
