lcr-modules:  
    varscan:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {tumour_id} {normal_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"

        scratch_subdirectories: ["mpileup"]

        options:
            mpileup: "-A -B -q 20 -d 8000" # countOrphan, noBaq, maxDepth -d 10000000, mapQuality, bedFILE (blank)
            somatic: 
                capture: "--min-coverage 20 --min-var-freq 0.01  --somatic-p-value 0.05 --strand-filter 0 --min-strands2 0 --validation 0 --output-vcf"
                genome: "--output-vcf" #this will have to be updated to sensible defaults
            unpaired:
                capture: "--min-coverage 20 --min-reads2 10 --min-avg-qual 20 --min-var-freq 0.01  --p-value 0.05 --strand-filter 0 --output-vcf 1 --min-strands2 0"
                genome: "--output-vcf" #this will have to be updated to sensible defaults

        vcf_header:
            hg19: "{MODSDIR}/headers/hg19.txt"
            hg38: "{MODSDIR}/headers/hg38.txt"
            grch37: "{MODSDIR}/headers/grch37.txt"
            grch38: "{MODSDIR}/headers/grch38.txt"

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            varscan: "{MODSDIR}/envs/varscan-2.4.4.yaml"
            bcftools: "{MODSDIR}/envs/bcftools-1.9.yaml"

        threads:
            somatic: 3
            unpaired: 3

        mem_mb:
            mpileup: 4000
            somatic: 12000
            unpaired: 12000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: False

