lcr-modules:
    
    ega_download:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_csv: "__UPDATE__" # csv sample table downloaded from EGA
            sample_metadata: "__UPDATE__" # basic metadata file. At the minimum, should contain EGA ID to sample_id mapping, seq_type of the sample, and genome_build.
        study_id: "__UPDATE__" # EGA study ID
        credentials_file: "__UPDATE__" # path to .json file with EGA credentials. Must be accessible only by file owner or group. Required keys are 'username' and 'password'

        scratch_subdirectories: []

        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"

        options:
            ega_file_index: "-b" # options for bam file indexing

        threads:
            ega_file_download: 8
            ega_file_index: 6

        resources:
            ega_file_download:
                mem_mb: 8000
                bam: 1
            ega_file_index:
                mem_mb: 4000

        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            capture:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
            mrna:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
