lcr-modules:

    mutsig:

        inputs:
            # Available wildcards: {seq_type}
            master_maf: "__UPDATE__"
            subsetting_categories: "__UPDATE__" # e.g. "data/metadata/level3_subsetting_categories.tsv"
        sample_set: ["__UPDATE__"]
        # Uncomment the following line to add a launch_date. Otherwise the current year-month will be used
        # launch_date: ""

        include_non_coding: True
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.1/generate_smg_inputs.R"
        src_dir: "{MODSDIR}/src/"

        scratch_subdirectories: []

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            wget: "{MODSDIR}/envs/wget-1.20.1.yaml"
            matlab: "{MODSDIR}/envs/matlab.yaml"

        threads:
            prepare: 4
            mutsig: 2

        resources:
            prepare:
                mem_mb: 50000
            mutsig:
                mem_mb: 250000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
