lcr-modules:

    fishhook:
        inputs:
            # Available wildcards: {seq_type} {projection}
            master_maf: "__UPDATE__"
            subsetting_categories: "__UPDATE__" # e.g. "data/metadata/level3_subsetting_categories.tsv"
            projection: ["grch37", "hg38"] # used to fill in {projection} wildcard in master_maf above
        sample_set: "__UPDATE__"
        # Uncomment the following line to add a launch_date. Otherwise the current year-month will be used
        # launch_date: ""

        include_non_coding: True
        prepare_mafs: "{SCRIPTSDIR}/generate_smg_inputs/1.1/generate_smg_inputs.R"
        src_dir: "{MODSDIR}/src/"

        options:
            include_silent_mutation: False # Include silent mutations in maf file
            tiles_size: 1000 # This is the size of tiles you want to split the genome into, if target_gene_list is set to False
            target_gene_list: False # Set to True if you want to use a gene list instead of tiling
            target_gene_list_only_protein_coding: True # Only include protein coding genes in gene list
            covariates:
            # comment out lines below if you do not want to use covariates
                chrom_hmm: "__UPDATE__"
                rep_timing: "__UPDATE__"

        conda_envs:
            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
            fishhook: "{MODSDIR}/envs/fishhook.yaml"

        threads:
            fishhook: 1

        resources:
            fishhook:
                mem_mb: 16000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
