lcr-modules:
    
    modkit:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"

        scratch_subdirectories: []


        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            modkit: "{MODSDIR}/envs/modkit-0.4.2.yaml"
            
        threads:
            pileup: 8

        options:
            header: "chrom\tstart\tend\tmodified_base_code\tscore\tstrand\tstart_position\tend_position\tcolor\tNvalid_cov\tpercent_modified\tNmod\tNcanonical\tNother_mod\tNdelete\tNfail\tNdiff\tNnocall"

        resources:
            step_1: 
                mem_mb: 2000
            
        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
