lcr-modules:
    
    sequenza:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
            merge_seqz: "{MODSDIR}/src/bash/merge_seqz.sh"
            filter_seqz: "{MODSDIR}/src/bash/filter_seqz.sh"
            run_sequenza: "{MODSDIR}/src/R/run_sequenza.R"
            cnv2igv: "{MODSDIR}/src/python/cnv2igv.py"

        scratch_subdirectories: []
        
        options:
            # TODO: Add params

        conda_envs:
            sequenza: "{MODSDIR}/envs/sequenza.yaml"
            
        threads:
            bam2seqz: 3
            merge_seqz: 1
            filter_seqz: 1
            sequenza: 8 

        mem_mb:
            bam2seqz: 10000
            merge_seqz: 10000
            filter_seqz: 20000
            sequenza: 100000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
