
name: Python package

on: [push]

 
jobs:
  linux:
    strategy:
      matrix:
        container:
        - 'debian:9'
        - 'debian:testing'
        - 'ubuntu:18.04'
        - 'ubuntu:devel'
        - 'centos:7'
        - 'centos:latest'   
        python-version: [3.6 , 3.7, 3.8, 3.9]  
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - run: cat /etc/*release

