lcr-modules:
    
    nanomethphase:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
            meth_calls: "__UPDATE__"
            vcf: "__UPDATE__" #needs to be a vcf with 10 columns with tumour snvs in column 10, or leave blank to use clair variant calls
        
        scratch_subdirectories: []

        conda_envs:
            nanomethphase: "{MODSDIR}/envs/nanomethphase.yaml"
            clair3: "{MODSDIR}/envs/clair3.yaml"
            whatshap: "{MODSDIR}/envs/whatshap.yaml"

        threads:
            methyl_call: 20
            nanomethphase: 50
            clair3: 50
            
        mem_mb:
            methyl_call: 25000 
            clair3: 25000
            whatshap: 25000
            
        clair3:
            model: "{CONDA_PREFIX}/bin/models/{model_name}" #Update to conda prefix of Clair3 environment and select appropriate model recommended r941_prom_hac_g360+g422 for GSC bams   

        pairing_config:
            promethION:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True

