lcr-modules:
    
    controlfreec:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            # sample_bam: "__UPDATE__"
            # sample_bai: "__UPDATE__"
            sample_bam: "/projects/rmorin/projects/tumour_contam/lcr-modules/demo/data/{sample_id}.bam"
            sample_bai: "/projects/rmorin/projects/tumour_contam/lcr-modules/demo/data/{sample_id}.bam.bai"

        genome_build:
            "grch38"
        reference:
            "out100m2_hg19.gem"

        # dirs:
            # inputs: "{MODSDIR}/"
            # outputs: "{MODSDIR}/"

        scratch_subdirectories: []
        
        conda_envs:
            controlfreec: "{MODSDIR}/envs/freec.env.yaml"
            bedtools: "{MODSDIR}/envs/bedtools.env.yaml"
            sambamba: "{MODSDIR}/envs/sambamba.env.yaml"
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"

        options:
            BedGraphOutput: FALSE
            # bedtools: /gsc/software/linux-x86_64-centos5/bedtools/bedtools-2.25.0/bin/bedtools
            breakPointThreshold: 0.8 #use 0.6 for more segments to get more CNVs
            breakPointType: 2
            chrFiles: /projects/rmorin_scratch/lcr-modules-references-DEV/genomes/hg19/freec/chr/
            chrLenFile: /projects/rmorin_scratch/lcr-modules-references-DEV/genomes/hg19/freec/hg19.len
            coefficientOfVariation: 0.05
            contamination: 0
            contaminationAdjustment: FALSE
            degree: 3&4
            forceGCcontentNormalization: 0
            gemMappabilityFile: /projects/rmorin_scratch/lcr-modules-references-DEV/genomes/hg19/freec/out100m2_hg19.gem
            minCNAlength: 1
            minimalSubclonePresence: 0.2
            maxThreads: 24
            ploidy: 2,3
            sambamba: /gsc/software/linux-x86_64/sambamba-0.5.5/sambamba_v0.5.5
            samtools: "{MODSDIR}/bin/samtools"
            #sex: XX or XY
            step: 10000
            telocentromeric: 50000
            window: 50000

        software:
            # FREEC: "/projects/dscott_prj/CCSRI_1500/lowpassWGS/envs/freec/bin/freec"
            FREEC_sig: "{MODSDIR}/etc/scripts/assess_significance.R"
            FREEC_graph: "{MODSDIR}/etc/scripts/makeGraph.R"
            FREEC_graph_chr: "{MODSDIR}/etc/scripts/makeGraph_Chromosome.R"
        
        conda_envs:
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            controlfreec: "{MODSDIR}/envs/freec.env.yaml"
            bedtools: "{MODSDIR}/envs/bedtools.env.yaml"
            sambamba: "{MODSDIR}/envs/sambamba.env.yaml"
        
        threads:
            controlfreec_run: 24
            calc_sig: 1
            plot: 1

        mem_mb:
            controlfreec_run: 8000
            calc_sig: 1000
            plot: 1000
        
        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
