lcr-modules:
    
    controlfreec:

        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"

        genome_build:
            "grch38"
        reference:
            "out100m2_hg19.gem"


        scratch_subdirectories: []
        
        conda_envs:
            controlfreec: "{MODSDIR}/envs/controlfreec.env.yaml"


        options:
            configFile: "{MODSDIR}/config/freec/config_WGS.txt"
            BedGraphOutput: FALSE
            breakPointThreshold: 0.8 #use 0.6 for more segments to get more CNVs
            breakPointType: 2
            chrFiles: /projects/rmorin_scratch/lcr-modules-references-DEV/genomes/hg19/freec/chr/
            chrLenFile: /projects/rmorin_scratch/lcr-modules-references-DEV/genomes/hg19/freec/hg19.len
            coefficientOfVariation: 0.05
            contamination: 0
            contaminationAdjustment: FALSE
            degree: 3&4 #3&4 for WGS; 1 for WES
            forceGCcontentNormalization: 0 #0 for WGS; 1 for WES
            gemMappabilityFile: /projects/rmorin_scratch/lcr-modules-references-DEV/genomes/hg19/freec/out100m2_hg19.gem
            minCNAlength: 1 #1 for WGS; 3 for WES
            minimalSubclonePresence: 20 #20 for WGS; 30 for WES
            maxThreads: 24
            ploidy: 2,3,4,5,6,7,8 #will select the ploidy that explains the most CNAs
            #sex: XX or XY
            step: 10000
            telocentromeric: 50000
            window: 50000

        software:
            FREEC_sig: "{MODSDIR}/etc/scripts/assess_significance.R"
            FREEC_graph: "{MODSDIR}/etc/scripts/makeGraph.R"
            FREEC_graph_chr: "{MODSDIR}/etc/scripts/makeGraph_Chromosome.R"

        
        threads:
            controlfreec_run: 24
            calc_sig: 1
            plot: 1

        mem_mb:
            controlfreec_run: 8000
            calc_sig: 1000
            plot: 1000
        
        pairing_config:
            genome:
                run_paired_tumours: False
                run_unpaired_tumours_with: "no_normal"
                run_paired_tumours_as_unpaired: True
